### ISSUE TITLE
Bookmarks getting reset

### ISSUE THREAD

**Issue by swapkh91** [wit-ai/wit#418] opened 2017-03-17 06:23 UTC
All the bookmark names have disappeared from the stories.

**Comment by Godoy** [comment] 2017-03-17 17:43
Same here :(

**Comment by tpizzle** [comment] 2017-03-19 09:32
Not to be whiny, but this bookmark thing seems to be getting worse and worse. I literally lost about 60% of my bookmarks today and my application basically fell apart because of it. It's pretty difficult just because half my logic may fall apart at any second!

**Comment by joinworldtv** [comment] 2017-03-24 05:55
Same here...

**Comment by adinhodovic** [comment] 2017-04-02 02:16
I'm still having a issue with this... Any updates on bug fixes?

**Comment by mashedkeyboard** [comment] 2017-04-16 19:29
Also having this issue.

**Comment by henriquenogueira** [comment] 2017-07-26 23:55
I am also facing this issue.

**Comment by blandinw** [comment] 2017-07-27 00:25
Can anyone give steps to reproduce this issue?

**Comment by l5t** [comment] 2018-01-22 01:21
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories

**Closed by l5t** 2018-01-22 01:21 UTC
Labels: bug, duplicate, stories
