### ISSUE TITLE
Identifying intent in different case

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2454] opened 2022-06-07 12:33 UTC
Hi,
We are using wit apps for our bots and all are working super good.
Recently we came across an issue in one of our trained app (App ID: 4344353432292657 ). I'm attaching the SS
![image_2022_06_07T12_12_11_813Z](https://user-images.githubusercontent.com/601711/172377630-b4431fa0-4582-4154-a4d0-2538bd58e834.png)
We have trained the below inputs for 'i_need_help' intent
banking
connect digo
lets digo

When we try 'connect digo' it is identifying the intent 'i_need_help'. 
![image_2022_06_07T12_12_50_274Z](https://user-images.githubusercontent.com/601711/172379110-c9375a34-4c85-46d7-a7c2-4924900a2aa1.png)

But if we try 'connect DIGO' it is not identifying  the intent 'i_need_help'. 
![image_2022_06_07T12_13_27_050Z](https://user-images.githubusercontent.com/601711/172379365-16ce3ddd-3c05-4633-b953-2458483e2100.png)

Are the intent examples case sensitive?
 Please provide a solution for handling this issue.

Thank you

**Comment by anjaly** [comment] 2022-06-08 03:53
Hi,

Any update on this. Client is still facing issues.

Thank you

**Comment by yuzh174** [comment] 2022-06-09 04:59
Hi @anjaly, sorry for the late reply. 

The issue is that you have both "connect" and "DIGO" trained as an utterance. The system will resolve to the closest match. You can test it out by send a request to the service to see the result. For example 

curl \
 -H 'Authorization: Bearer <-- You Token -->' \
 'https://api.wit.ai/message?v=20220608&q=connect%20DIGO'

I did a test. "connect digo" resolves to "connect" intent and "connect DIGO" resolves to "i_need_help". 

To fix this, you can try to also train "digo" and even "connect digo" to resolve to i_need_help if that's expected.

**Comment by Barbog** [comment] 2023-04-18 09:44
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.

**Closed as not planned by Barbog** 2023-04-18 09:44 UTC
