### ISSUE TITLE
Spanish speech not working

### ISSUE THREAD

**Issue by pablopalomino96** [wit-ai/wit#1687] opened 2020-04-03 13:12 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When I send a `wav` file through POST /speech I obtain an empty text. I am using Spanish Language in my App.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```shell
curl -XPOST 'https://api.wit.ai/speech?v=20170307' \
   -i -L \
   -H "Authorization: Bearer <MyToken>" \
   -H "Content-Type: audio/wav" \
   --data-binary @<MyFile>.wav
```
Response
```shell
HTTP/1.1 100 Continue
Date: Fri, 03 Apr 2020 13:01:23 GMT

HTTP/1.1 200 OK
Content-Type: application/json
Date: Fri, 03 Apr 2020 13:01:25 GMT
Date: Fri, 03 Apr 2020 13:01:25 GMT
Connection: keep-alive
Content-Length: 35

{
  "_text": "",
  "entities": {}
}
```
My audio file is a valid wav file and says some numbers. I try with some languages like German or English and It works.

**What is the expected behavior?**
I expected `_text` field to contain a non-empty String.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
**AppID**: 2680716112251870

**Comment by jtliao** [comment] 2020-04-03 14:14
Any chance you can attach the audio file you're using? The speech API for Spanish is working fine for me.

**Comment by pablopalomino96** [comment] 2020-04-03 14:29
> Any chance you can attach the audio file you're using? The speech API for Spanish is working fine for me.

Of course, here it is: [wav file](https://file.io/3dLeom)

TY :smiley:

**Comment by jtliao** [comment] 2020-04-03 14:42
The API is working correctly for me, though I noticed when sending the request to your app, that your app is in French, not Spanish. Can you try again after setting the language correctly?

**Comment by pablopalomino96** [comment] 2020-04-03 14:47
> The API is working correctly for me, though I noticed when sending the request to your app, that your app is in French, not Spanish. Can you try again after setting the language correctly?

It's because I've been trying some languages. I just set the language to Spanish again and I keep getting the same empty text.

**Comment by jtliao** [comment] 2020-04-03 14:56
can you try creating a new app? i can't reproduce this at all

**Comment by pablopalomino96** [comment] 2020-04-03 15:00
> can you try creating a new app? i can't reproduce this at all, even with your app's token and audio file

Of course, done.
New **Application Id** is 521690455382111

**Comment by jtliao** [comment] 2020-04-03 17:02
Am able to reproduce now, looking into the issue.

**Comment by jtliao** [comment] 2020-04-04 00:45
This should be fixed now, can you give it another shot?

**Comment by dirkar** [comment] 2020-04-04 06:46
Recognition russian speech to text is working now, thanks

**Comment by pablopalomino96** [comment] 2020-04-04 10:29
It's working now! TY so much @jtliao :tada:

**Closed** 2020-04-04 10:30 UTC
