### ISSUE TITLE
App stuck in training

### ISSUE THREAD

**Issue by liamMwalls** [wit-ai/wit#1119] opened 2018-06-21 10:46 UTC
Do you want to request a feature, report a bug, or ask a question about wit?
question

What is the current behavior?
App is stuck in training.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Inserted a lot of values into an entity (~10k). App has been in ongoing training since then.

What is the expected behavior?
Training should've finished by now.

What is the App ID where you are experiencing this issue (if applicable)?
5af55db6-a9c2-44ad-8188-64168d7105845af55d

**Comment by mminchev** [comment] 2018-06-21 10:49
I am facing the same issue. All wit.ai apps that I trained in the last 24h are stuck in "Training status: ongoing".

**Comment by serdalbayram** [comment] 2018-06-21 10:51
same for me

**Comment by klemensz** [comment] 2018-06-21 12:42
Same here. App ID: 5902737c-e922-4695-bed3-874f70abb502

**Comment by mminchev** [comment] 2018-06-21 12:49
This is really annoying. We are talking about a production environment here and it is not the first time that something suddenly stops working. This particular problem exists for at least 12 hours now.

**Comment by blandinw** [comment] 2018-06-21 14:18
Looking into it. Adding 5b1f8b7e-fb79-4cb0-ab6d-98b960e403eb to the list

**Comment by mminchev** [comment] 2018-06-21 14:38
Thanks a lot, @blandinw.

**Comment by hactar** [comment] 2018-06-21 14:58
Please check 5a2934a4-a921-48f2-8439-960637f89aba too.

**Comment by blandinw** [comment] 2018-06-21 17:28
Quick update:
- the training jobs are not dropped, and will be processed eventually (we're seeing between 20 minutes and 8 hours of lag at the moment)
- some bad users are hogging the training queue, impacting other users
- we used to drop these very heavy training jobs
- we deployed a new training system which is more reliable and does not drop heavy training jobs easily
- ironically, now we're better at making sure training jobs are never lost, but it means the bad jobs are never lost too
- we'll take steps to 1) mitigate the current situation and remove lag caused by bad users and 2) tweak the system to explicitly drop these bad users

**Comment by blandinw** [comment] 2018-06-22 00:59
@hactar thanks for the idea and positive energy!

Bad users are people uploading datasets endlessly and/or creating a very large number of entities. We do not want to put the burden on users to self-regulate in terms of training volume. The system will be smart enough to handle all these scenarios.

What happened here is very situational, the system had just been deployed and did not have enough data to make good decisions about scheduling.

In any case, the problem is fixed now and all apps should be properly trained. We identified a series of steps to make the system smarter that we'll implement in the following days and weeks. As a team, we're excited to be shipping this as this will fix many of the issues we faced with the old system + give more visibility to users via the API and web UI.

**Comment by MahmoudSalah17** [comment] 2018-06-23 00:58
I have the same problem.
App ID : 5a0d8271-1624-4fdb-847f-ffa194228762

**Comment by stopachka** [comment] 2018-06-25 18:46
Thanks for the patience everyone! We've recently deployed new infra on this, which though it's painful now will become much more robust in the feature. I'll reopen this for now, and keep addressing training issues until we get to a full fix

**Comment by individual11** [comment] 2018-06-26 14:59
Our app -> 583273ad-575f-4ad3-a801-fe95d236ce57 is back in the slow training loop when we added a single keyword. We are getting responses, very slowly, from previous keywords and intents, but if we use the new keyword, it never responds.

**Comment by l5t** [comment] 2018-06-26 18:57
just restarted your training.

**Comment by individual11** [comment] 2018-06-28 18:10
@l5t can you tell me what's triggering it? It's back in the loop again, and I was just testing things it was already trained on.

**Comment by stopachka** [comment] 2018-07-05 22:37
Hey team, this week we landed an update to the UI, which should show you much more information for training. This includes:

- The Training State:
  - Is it scheduled? If yes, the time it is scheduled to train
  - Is the training happening now? If yes, the time it took to train your app last time

This can help bring more clarity to errors here. If training is scheduled too far into the future for your app for example. Or, if it is ongoing, and it says the last time it took 20 seconds, but you see it much longer, we know there's some bug. 

Please include what you see on that state 

![image](https://user-images.githubusercontent.com/984574/42351346-628abc14-8069-11e8-8e1d-c0c190909f0c.png)

**Comment by srdjanfolic** [comment] 2018-07-07 12:31
On the ongoing status there is no info how long it took last time to train. Just says "Your app is currently training" and nothing happens

**Comment by 91ns** [comment] 2018-07-08 00:12
@blandinw does the mentioned scheduled delays "20 minutes to 8 hours" vary on app bases? I have apps that go through training quickly, while others show "scheduled" to be trained after 8 hours.
 This app for example 5b0515c8-5c31-4249-8c05-faae08c7465a

**Comment by Arsenikr** [comment] 2018-07-18 15:18
stuck in ongoing: 5b4f3f49-ef4d-45cd-a11e-b0be7df5e66a

**Comment by stopachka** [comment] 2018-07-20 18:11
Two more app-ids

5b3f143e-65fd-449d-92b0-be742863dfaf
5b51c011-ad55-4cfb-84f8-3b45740f3b2d

From #1150

**Comment by blandinw** [comment] 2018-07-22 01:30
We sincerely apologize for the inconvenience and slow trainings.
All mentioned apps have been retrained since and we added a UI element to give you more visibility as to when your app is scheduled to be trained (API coming very soon).

We've also made reliability and optimization improvements to the current system, we're working on some fairness improvements so that smaller apps aren't slowed down by bigger apps.
Please comment here or open a new GitHub issue if you encounter more issues.

Closing this now.

**Closed by blandinw** 2018-07-22 01:30 UTC
Labels: investigating

**Comment by jhoncode** [comment] 2018-12-12 00:00
Please check : App Id: 2997680370257847 too.

**Comment by idanadut** [comment] 2019-03-25 15:01
Hi @blandinw , having the same issue (have been training for hours) - can you check please:
https://wit.ai/idanadut/ivory/entities
App Id: 1674535315981487

**Comment by patapizza** [comment] 2019-03-25 17:31
Hi @idanadut, your app is now trained. Please open up a new or comment on a recent open issue next time, it makes it easier to track. Thanks!

**Comment by shukriwinapp** [comment] 2019-04-16 03:22
please check : App ID : 59bbe086-feab-4b4b-9b54-cab99a996261, im having the same problem to

**Comment by amtdevops** [comment] 2019-06-03 05:56
please check: APPA ID:  2159428820836844. Facing the same issue for last 2 days.

**Comment by anjaly** [comment] 2019-06-11 11:51
please check: APP ID: 2159428820836844.

**Comment by anjaly** [comment] 2019-06-14 09:15
Hi team,
Please update the scheduling time in the below app

2463006727052618

Its urgent.

**Comment by aforaleka** [comment] 2019-06-14 17:34
seems like your app's done training @anjaly

**Comment by offengenden** [comment] 2019-06-16 06:08
Hi,

Please check my app too!!!
2167709739965060

😭

Thank you

**Comment by moraitis55** [comment] 2019-08-05 07:20
/hello
my app is stuck for 3 days now, can you take a look?
2702444876450736

**Comment by thisishantzz** [comment] 2019-09-05 09:17
Hi, my app (app ID: 2635221853156788) is stuck in training too. Is there something wrong that I am doiing?

**Comment by SSGChennai** [comment] 2019-10-22 07:12
Hi, my app status is Ongoing for 7 days now, can you take a look?
App id : 2043897882379151.

**Comment by kingseaeast** [comment] 2019-10-23 08:03
@SSGChennai  looks like we're tracking this issue in https://github.com/wit-ai/wit/issues/1571

**Comment by ankit-27** [comment] 2019-11-19 13:35
Hi, my app is showing ongoing from the past 2 days. Please, can you look?
App ID: 2536731159742728

**Comment by eurocharts** [comment] 2019-12-25 05:53
Hello,
Can You look on my app?

Currently training last 5 days

App id: 2184728738274083

Thank You!

**Comment by Chris-Ar** [comment] 2020-08-28 07:33
Hello,

Reviving an old thread but our app is also stuck at "Training Ongoing" for a day now.
Used to finish in around 1 minute.

App id: 3345749878784230

Is there anything we can do on our side to resolve this?
Best Regards.

**Comment by SamuelJansen** [comment] 2021-05-25 04:56
My is pretty clean.

Four uterances, few intents and entities.
And still... more than a day to complete trainning

Such a beaviour should be explicit in docmentation.

App ID:
112010790969863

Funny thing is that the message says last trainning took abou 4 minutes, witch is not true at all
![image](https://user-images.githubusercontent.com/46162680/119441497-986d1c00-bcfc-11eb-98fb-1f39bff14c7c.png)

================================================

Update.

For me it seems that the trainning queue actually stuck, even if there is "free room" for a trainning batch.

A work arround that has been working for me is to update a single utterance
(lets say after 2 hours of "trainning stuckiness" withou finishing it).

It causes the trainning batch to restart and "unstuck" (and eventualy complete).

================================================

For me, it seems that if we could only train after certain ammount of utterances in editting in plataform, it would perform better
A work arround is to post utterances through API
https://wit.ai/docs/http/20200513#post__utterances_link

This way, the "trainning batch" is started only once insted of every time you make an edditting in WitAi plataform

**Comment by SamuelJansen** [comment] 2021-05-25 14:32
Update.

For those who are still facing this issue. 
The trainning queue seems to actually stuck.

A work arround that has been working for me is to update a single utterance 
(lets say after 2 hours of trainning withou finishing it).

It forces the trainning batch to restart and, eventualy, complete.

**Comment by PanoSpent** [comment] 2021-05-26 06:13
My app is stuck too for more than a day. 

339053820531515 @

**Comment by sportsman1990** [comment] 2021-08-12 10:43
My app is still on training ongoing. App ID:
1160394380993056

**Comment by codeunifier** [comment] 2021-12-20 16:43
Also experiencing this for the first time today. Been stuck on "scheduled" for over an hour. A way to manually kill the training or restart the training would be great, especially if it's stuck in scheduled and hasn't actually started the training itself yet.

**Comment by Ananyag02** [comment] 2022-01-04 09:21
Hi, my app has been on "ongoing" for hours now. kindly restart it. 
https://wit.ai/apps/596907408234734/entities

**Comment by hvo408-brightplan** [comment] 2022-01-07 16:12
I hope someone is monitoring this closed thread and help, but my app is stuck too ("Training ongoing") for more than a week now. App id is 1984954734884414.

**Comment by PanoSpent** [comment] 2022-01-07 16:48
Hi all,

I had the same issue and solved it by downloading the app and upload it to
a new one. After a really long period of time my app got unstuck.

Hope it helps.

Best Regards,

Panagiotis

**Comment by hvo408-brightplan** [comment] 2022-01-10 23:18
Thanks so much @PanoSpent. That works for me
