### ISSUE TITLE
Upper interval rounded up to next hour or minute

### ISSUE THREAD

**Issue by brightsparc** [wit-ai/wit#196] opened 2016-02-20 05:12 UTC
Hi,

If I include the phrase "Monday 7:30pm to 8pm", this results in the upper limit of "9pm".  If I specify the minutes "Monday 7:30pm to 8:00pm" it appears to correctly detect the precision, although the interval upper bound is 8:01pm.

Is it the case that the library always adds +1 to the upper bound of the interval eg minute/hour?

This behaviour is different to the experience when testing directly on http://duckling.wit.ai

Cheers,
Julian.

**Comment by l5t** [comment] 2016-02-20 05:20
This is by design. We may revisit this decision that we took at the beginning. But for now, Wit will give you the excluded upper bound. You can rely on the grain to infer the included upper bound

**Comment by brightsparc** [comment] 2016-02-20 05:44
Hi,

Thanks, yes I can infer the upper bound with brain for 8pm to 9pm example
where the grain is hours.  But for the 7:30pm to 8pm, the grain is returned
as 'minute' for the 8pm which makes it difficult to infer that I should
round down.  eg:

            "type": "interval",
            "from": {
              "value": "2016-02-20T19:30:00.000+11:00",
              "grain": "minute"
            },
            "to": {
              "value": "2016-02-20T21:00:00.000+11:00",
              "grain": "minute"
            },

Would it be possible to change the grain to 'hour' in this case?

Cheers,
Julian.

**Comment by martinraison** [comment] 2016-04-21 23:21
I agree that the rounding of "monday 7:30pm to 8pm" is inconsistent with the grain. Flagging it as a bug.

**Comment by almostimplemented** [comment] 2017-03-13 23:20
I have identified the root cause of this bug and have a fix for it in Duckling. It does break an existing rule, and some discussion is needed to determine whether the right thing to do is change the _production rule_ or change its _semantics_ (probably the former). 

https://github.com/wit-ai/duckling/issues/221

**Comment by l5t** [comment] 2018-12-18 22:58
Closing, feel free to reopen an issue in Duckling specifically https://github.com/facebook/duckling

**Closed by l5t** 2018-12-18 22:58 UTC
Labels: bug
