### ISSUE TITLE
wit.ai converse API call returning wrong action

### ISSUE THREAD

**Issue by swativoip** [wit-ai/wit#311] opened 2016-09-01 08:31 UTC
converse API call from my java code is returning wrong action for the input message. Its happens most of the time. If i try the story execution in wit.ai platform it works fine. but through my application its failing. Can you please help/provide pointers to resolve this issue?

**Comment by magnusburton** [comment] 2016-10-10 15:30
Same for me, just started today.

**Comment by jcdalton2201** [comment] 2016-10-27 14:29
+1 for this.

**Comment by Rclemens** [comment] 2016-12-01 20:32
I have the same issue. When using a bookmark it doesn't return the action at all

**Comment by asssmidt** [comment] 2016-12-16 00:38
Same here. Anyone figured it out?

**Comment by Rclemens** [comment] 2016-12-16 07:56
Nope, I'm investigating the conversation api of IBM Watson.

**Comment by l5t** [comment] 2016-12-16 16:51
@asssmidt  can you share the URL of your Wit app?

**Comment by asssmidt** [comment] 2016-12-19 12:55
So Sorry, I didn't see this message Laurent.

Our Wit app URL: https://wit.ai/assersmidt/husetsforsikring/stories

Thanks for any help/input on this.



On Fri, Dec 16, 2016 at 5:51 PM, Laurent Landowski <notifications@github.com

**Comment by l5t** [comment] 2016-12-19 13:23
Can you provide the steps to reproduce the errors also? Thanks

**Comment by zakaria-elbadri** [comment] 2016-12-19 14:51
Hi Laurent,

This is the story concerned : https://wit.ai/assersmidt/husetsforsikring/stories/9e1fc0f6-1a4f-487e-afdf-7ba4fa03abe7

In wit.ai chat we are trying this scenario : 
User : hvad hedder du?
Bot : Mit serienummer er 2716057, men jeg har faktisk ikke noget navn endnu. Hvad hedder du?
User : Jeg hedder Daniel
Bot : Hej Daniel, hyggeligt at møde dig :) Hvad synes du jeg skal hedde?
User : hvad med Lisa?
Bot : Lisa lyder faktisk godt! Det vil jeg foreslå til mine programmører :)

When we try the same scenario from Facebook messenger it's not going for all the story, so it's just answering for the first question, and then the second one is starting with another story:
User : hvad hedder du?
Bot : Mit serienummer er 2716057, men jeg har faktisk ikke noget navn endnu. Hvad hedder du?
User : Jeg hedder Daniel
Bot : Bip bop! Jeg er blot en simpel chatbot og der er stadig meget, jeg ikke forstår - undskyld! Brug menuknappen med de tre linjer til venstre for tekstfeltet til at finde rundt i mig. **(This response is from another story)**

This is the implementation on the NodeJs project (The same as https://github.com/wit-ai/node-wit/blob/master/examples/messenger.js) : 

const wit = new Wit({
  accessToken: WIT_TOKEN,
  actions,
  logger: new log.Logger(log.INFO)
});

const sender = event.sender.id;
const sessionId = findOrCreateSession(sender);
const {text, attachments} = event.message;

if (attachments) {
fbMessage(sender, 'Sorry I can only process text messages for now.').catch(console.error);
} else if (text) {
     wit.runActions(
     sessionId,
     text,
     sessions[sessionId].context
).then((context) => {
    console.log('Waiting for next user messages');
    sessions[sessionId].context = context;
}).catch((err) => {
console.error('Oops! Got an error from Wit: ', err.stack || err);
})
}

**Comment by asssmidt** [comment] 2016-12-19 15:01
Hi Laurent, not sure if you received the response from my co-worker, so
here goes again to be sure:

Hi Laurent,

This is the story concerned : https://wit.ai/assersmidt/
husetsforsikring/stories/9e1fc0f6-1a4f-487e-afdf-7ba4fa03abe7

In wit.ai chat we are trying this scenario :
User : hvad hedder du?
Bot : Mit serienummer er 2716057, men jeg har faktisk ikke noget navn
endnu. Hvad hedder du?
User : Jeg hedder Daniel
Bot : Hej Daniel, hyggeligt at møde dig :) Hvad synes du jeg skal hedde?
User : hvad med Lisa?
Bot : Lisa lyder faktisk godt! Det vil jeg foreslå til mine programmører :)

When we try the same scenario from Facebook messenger it's not going for
all the story, so it's just answering for the first question, and then the
second one is starting with another story:
User : hvad hedder du?
Bot : Mit serienummer er 2716057, men jeg har faktisk ikke noget navn
endnu. Hvad hedder du?
User : Jeg hedder Daniel
Bot : Bip bop! Jeg er blot en simpel chatbot og der er stadig meget, jeg
ikke forstår - undskyld! Brug menuknappen med de tre linjer til venstre for
tekstfeltet til at finde rundt i mig. *(This response is from another
story)*

This is the implementation on the NodeJs project (The same as
https://github.com/wit-ai/node-wit/blob/master/examples/messenger.js) :

const wit = new Wit({
accessToken: WIT_TOKEN,
actions,
logger: new log.Logger(log.INFO)
});

const sender = event.sender.id;
const sessionId = findOrCreateSession(sender);
const {text, attachments} = event.message;

if (attachments) {
fbMessage(sender, 'Sorry I can only process text messages for
now.').catch(console.error);
} else if (text) {
wit.runActions(
sessionId,
text,
sessions[sessionId].context
).then((context) => {
console.log('Waiting for next user messages');
sessions[sessionId].context = context;
}).catch((err) => {
console.error('Oops! Got an error from Wit: ', err.stack || err);
})
}

On Mon, Dec 19, 2016 at 2:23 PM, Laurent Landowski <notifications@github.com

**Comment by asssmidt** [comment] 2016-12-22 00:33
@l5t Did we provide enough info above to look more into it?

Thanks!

**Comment by asssmidt** [comment] 2016-12-25 16:10
@l5t Did we provide enough info above to look more into it?

Thanks!

**Comment by l5t** [comment] 2016-12-27 23:41
Thanks for the details. I cloned your app here and I think I understand what's going on

- Your fallback story needs to have a intent entity. As explained in the docs/recipes:  Only trait entities have their value influence the prediction. For non-trait entities, the value is ignored with regards to action prediction. So you need to have trait entity to distinguish stories
![image](https://cloud.githubusercontent.com/assets/6992759/21510535/60651a2c-cc49-11e6-9602-b8bf97c5c453.png)

- [not mandatory] Same you probably need to have an intent on the "Jeg hedded Daniel" part of your story like this:
![image](https://cloud.githubusercontent.com/assets/6992759/21510548/9806d006-cc49-11e6-85c1-1208c0563853.png)

- Finally and **most importantly** you need to update the context with the name that you detect from the entity and pass it to your next call to converse. The Chat Mode on the Wit console emulate this but you need to take care of the context on your side
![image](https://cloud.githubusercontent.com/assets/6992759/21510641/bd9e2f98-cc4a-11e6-95e0-3363bae5e715.png)

and on your code, something like this
![image](https://cloud.githubusercontent.com/assets/6992759/21510646/d1483c32-cc4a-11e6-885d-7ff944f20d23.png)
You can check my wittyfiddle here: https://wit-ai.github.io/witty-fiddle/?id=d5b1505d74fb548dbd4ba53587d4198e

Hope it helps

**Comment by l5t** [comment] 2018-01-22 01:26
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories

**Closed by l5t** 2018-01-22 01:26 UTC
