### ISSUE TITLE
Something went wrong. Weve been notified

### ISSUE THREAD

**Issue by shinmar** [wit-ai/wit#1122] opened 2018-06-22 03:40 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Yesterday entity creation is working, but today , i didnt change anything,  it throws an error response 
 { error: 'Something went wrong. We\'ve been notified',
     code: 'unknown' } }

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**

5b2c6e85-9ead-44fe-9c00-494955a99de2

**Comment by blandinw** [comment] 2018-06-22 04:16
Are you using our web interface or HTTP API?
Will mark as a duplicate of #1120 for now

**Comment by blandinw** [comment] 2018-06-22 04:16
Please comment with more info

**Closed by blandinw** 2018-06-22 04:16 UTC

**Comment by shinmar** [comment] 2018-06-22 05:08
I'm using the HTTP API 

This is the sample request
var options = {
    url: process.env.ENTITY_URI+ "/entities?v=20170307",
    method: "POST",
    data: entity,
    headers: {
      Authorization: "Bearer " + auth,
      "Content-Type": "application/json"
    }
  };

  return axios(options)
    .then(res => res)
    .catch(err => {
      throw err;
    });

**Comment by stopachka** [comment] 2018-06-25 18:51
most likely this was caused by #1120 -- should be back now
