### ISSUE TITLE
Deployment not working

### ISSUE THREAD

**Issue by adhilmunna** [wit-ai/wit#2578] opened 2023-01-16 20:40 UTC
App id - 1295379967985062

Deployment not working. When clicked, it shows 'deploying to runtime' but deployment doesnt happen even after waiting for hours.

No error message 

Expected to complete deployment in a minute or 2

**Comment by harisvsulaiman** [comment] 2023-01-17 06:16
The deployment network request from the composer fails with this error code , but the ui doesn't update with an error state .
It simply shows 'deploying' even-though it has failed.
 

```{
   "error": "Something went wrong. We've been notified",
   "code": "unknown"
}%
```

@wangpingsx

**Comment by adhilmunna** [comment] 2023-01-17 06:54
@wangpingsx

Found out what is causing this. Apparently, when grouping is there, deployment fails. Removed all groupings and deployment worked.

**Comment by yuzh174** [comment] 2023-01-18 01:06
Thanks for reporting the issue. Grouping should work. I see you still have group in the app. Do you still see problems with grouping?

**Comment by adhilmunna** [comment] 2023-01-18 05:46
> Thanks for reporting the issue. Grouping should work. I see you still have group in the app. Do you still see problems with grouping?

@yuzh174 Yes, this app has grouping. This one does not deploy. I tried with a different app, this one's exact replica but with no grouping and it deployed.

**Comment by adhilmunna** [comment] 2023-01-18 05:58
Tried deploying other apps. Putting more info about them here so that you can do a comparison @yuzh174 

1351635972341468 - error code 99
665964985113038 - This one deploys (fails when another user that has access tries deployment)

both have no grouping. At this point im not even sure if grouping is causing the issue.

**Comment by yuzh174** [comment] 2023-01-18 18:30
Thanks this is helpful. We will investigate these apps.

**Comment by yuzh174** [comment] 2023-01-20 17:31
Hi @adhilmunna, please try again. The issue should be fixed now

**Comment by adhilmunna** [comment] 2023-01-20 17:35
> Hi @adhilmunna, please try again. The issue should be fixed now

@yuzh174 Thanks. Checked. Its working.

This is such a great experience. Getting prompt support from a global project team. 👌🏻More power to you.❤️❤️❤️

**Comment by adhilmunna** [comment] 2023-01-20 18:09
@yuzh174 Another issue has popped up. Shows there is validation error. But no errored modules are highlighted. When the page is refreshed and power source is connected, app (play) works fine in wit. but deployment fails (then works randomly without making any changes).
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36878485/213774720-99e7fc4f-cd37-4dc7-a07a-61b722dd90ba.png">

app id - 901909424181036

**Comment by yuzh174** [comment] 2023-01-23 19:31
Glad to hear now it is working. We will look at the validation error issue.

**Comment by adhilmunna** [comment] 2023-02-02 15:49
@yuzh174 Now no matter what, deployment fails. Could you please give an update? Client is Waiting for deployment.

**Comment by yuzh174** [comment] 2023-02-02 21:50
We have been looking at the app, but haven't seen the reason to cause failures. Now that you have another repro, we will look into it again update ASAP.

**Comment by CleanestMink126** [comment] 2023-02-08 17:30
@adhilmunna 
Hello, I've redeployed the app for you and didn't run into any failures (took about 5 minutes). It's possible if any concurrent writes happen to the graph during deployment, it could cause problems (we're working on addressing this issue), so that may be the root cause. For now, while deploying make sure to not edit the graph in other windows or reload the window.

Let me know if it's still persistent, if so, it may have to do with permissions and we can look deeper into that.

**Comment by adhilmunna** [comment] 2023-02-08 17:34
@CleanestMink126 tried with a single tab opnen. Same outcome . Validation error. But i could test app. Works fine. Cant deploy

**Comment by adhilmunna** [comment] 2023-02-14 14:03
@CleanestMink126 A quick update. The deployment seems to be working fine now. Let me try deployments for next couple of days, will notify you if the issue resurfaces.

**Comment by CleanestMink126** [comment] 2023-02-14 17:40
@adhilmunna Awesome! We rolled out some changes yesterday that streamlined the deployment process, so that likely fixed the issue. But let us know if you see any more errors.

**Closed as completed by CleanestMink126** 2023-02-14 17:40 UTC
