### ISSUE TITLE
getting error when post data in uttarence api.

### ISSUE THREAD

**Issue by surajsingh92** [wit-ai/wit#1926] opened 2020-09-24 04:52 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a bug

**What is the current behavior?**
when i post data in Utterance  api . i am always getting the same error msg which is "Failed to validate utterance at index 0. Could not find entity" but i have already this entity in  entity section. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
i am posting the following data in utterance api .
[{
	
		        "text": "I want to fly to sfo",
			        "intent": "flight_request",
			        "entities": [
			          {
			            "entity": "wit$location",
			            "start": 17,
			            "end": 20,
			            "body": "sfo",
			            "entities": []
			          }
			        ],
			        "traits": []
}]
when i post this data i am getting above error msg. i have already created the wit$location entity in entity section of wit.

**What is the expected behavior?**
should not get this error msg. 

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
324212385527094

**Comment by patapizza** [comment] 2020-09-25 23:17
Duplicate of https://github.com/wit-ai/wit/issues/1917.

**Closed as completed by patapizza** 2020-09-25 23:17 UTC
