### ISSUE TITLE
500'ing

### ISSUE THREAD

**Issue by tpizzle** [wit-ai/wit#493] opened 2017-04-13 20:40 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Getting 500s
**What is the current behavior?**
Can't have any conversations
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send a message to a chatbot and see if you get responses if they require using an action
**What is the expected behavior?**
My actions would run on my backend and produce the relevant data

**Comment by blandinw** [comment] 2017-04-13 21:25
What's your app-id and an example request?

**Comment by tpizzle** [comment] 2017-04-13 21:32
App ID: 58d2c3e6-debc-4433-899a-eee73e38a912

Example: 

Net::HTTP::Post https://api.wit.ai/converse?q=%E2%8F%AD&session_id=b4da1ea4-7f27-4d0e-bb29-75ee7fbfddb5
Apr 13 14:24:20 ip-172-31-26-53 rails_app_qa:  I, [2017-04-13T21:24:19.987702 #1237]  INFO -- : Error attempting to process Facebook message: HTTP error code=500
Apr 13 14:24:20 ip-172-31-26-53 rails_app_qa:  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
Apr 13 14:24:20 ip-172-31-26-53 rails_app_qa:   /var/app/current/lib/bot_mechanic.rb:197:in `block in req'
Apr 13 14:24:20 ip-172-31-26-53 rails_app_qa:  /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:584:in `start'
Apr 13 14:24:20 ip-172-31-26-53 rails_app_qa:  /var/app/current/lib/bot_mechanic.rb:228:in `__run_actions'
Apr 13 14:24:20 ip-172-31-26-53 rails_app_qa:  /var/app/current/lib/bot_mechanic.rb:192:in `req'
Apr 13 14:24:20 ip-172-31-26-53 rails_app_qa:  /var/app/current/lib/bot_mechanic.rb:61:in `converse'
Apr 13 14:24:20 ip-172-31-26-53 rails_app_qa:  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/wit-4.1.0/lib/wit.rb:184:in `run_actions'

I have a `BotMechanic` class that wraps the wit-ruby gem, but it's all the same stuff as in the gem

**Comment by blandinw** [comment] 2017-04-13 22:51
I'm able to query your app using `curl`:

```
λ curl -XPOST 'https://api.wit.ai/converse?session_id=58d2c3e6-debc-4433-899a-eee73e38a912&access_token=[redacted]&q=%E2%8F%AD'
{
  "confidence" : 0.001034472605090547,
  "type" : "action",
  "action" : null,
  "entities" : {
    "next" : [ {
      "confidence" : 0.8489258218229924,
      "type" : "value",
      "value" : ""
    } ]
  }
```

**Comment by blandinw** [comment] 2017-04-13 22:52
We (and FB...) had a small outage. I've patched that part to make it more robust. It may be what caused the issue. This should not happen again in the future (unless facebook.com is down).
Can you confirm that the issue is fixed on your side?

**Closed by blandinw** 2017-04-13 22:52 UTC
Labels: bug

**Comment by tpizzle** [comment] 2017-04-13 23:20
Thanks a ton @blandinw !
