### ISSUE TITLE
Web crashed when click on dropdown in the last live utterance. Wit v2

### ISSUE THREAD

**Issue by dogcalas** [wit-ai/wit#1735] opened 2020-05-13 21:57 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
- Report a *bug*

**What is the current behavior?**
Inside  Understanding  view in v2, when I click in the dropdown button on the last "live utterance" item. 
![download](https://user-images.githubusercontent.com/2521769/81869583-e243f380-9539-11ea-89ee-49fd92b6b18c.png)

the screen go blank and this message is showed in browser console.
```
929m2ZL_PxA.js?_nc_x=Ij3Wp8lg5Kz:51 ErrorUtils caught an error:

Cannot read property 'entity_type' of undefined

Subsequent errors won't be logged; see https://fburl.com/debugjs.
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Open a project.
- Go to the last utterance
- Click on dropdown button  

**What is the expected behavior?**
Should show the Train and validate button

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
3164994740391651

**Comment by patapizza** [comment] 2020-05-13 22:12
Thanks for reporting! We're looking into it.

**Comment by patapizza** [comment] 2020-05-14 01:22
Root cause identified, should be fixed in a few hours. Thanks for your patience.

**Comment by patapizza** [comment] 2020-05-14 05:57
This is now fixed.

**Closed by patapizza** 2020-05-14 05:57 UTC
Labels: bug, investigating
