### ISSUE TITLE
[Bug] Intent classification not working

### ISSUE THREAD

**Issue by touchaponk** [wit-ai/wit#966] opened 2018-02-09 09:58 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Intent classification (entity of 'trait' type) is not returning any result no matter what sentence I put in, even if it's an exact match. This starts happening 1 day ago

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just train the intent with lots of data and try
https://wit.ai/aongwachi1/inter06-th/entities
this is one of the example

**What is the expected behavior?**
It should return matching value

**What is the App ID where you are experiencing this issue (if applicable)?**
many of them, including 5a7c8363-d226-4a58-8226-39c9d6bc9a92

**Comment by patapizza** [comment] 2018-02-09 18:05
Thanks for reporting, I'll get a look.

**Comment by patapizza** [comment] 2018-02-09 23:00
@touchaponk What are the other apps having issues? Was `kbchatbot-en` working before?
Anybody else experiencing this?

**Comment by touchaponk** [comment] 2018-02-09 23:49
@patapizza many of them actually, here's another one
5a7c8363-d226-4a58-8226-39c9d6bc9a92
from what I notice if I train using the console UI it works fine, however once I use API to train the intent all at once it breaks

**Comment by patapizza** [comment] 2018-02-12 17:16
@touchaponk To be clear, what do you mean by "using the API to train the intent"? Do you mean providing new samples to `POST /samples`?

**Comment by touchaponk** [comment] 2018-02-12 19:30
@patapizza I'm using `PUT https://api.wit.ai/entities/$ENTITY_ID` API to update the expressions

**Comment by josephlingzb** [comment] 2018-02-13 02:09
Hi @patapizza, am experiencing the same issue. Im using PUT https://api.wit.ai/entities/$ENTITY_ID to update the expressions. The new expressions can be seen on the wit.ai console, but inputting the exact expression never goes to the correct intent. 

Old intents removed through this API also are removed on the wit.ai console, but when downloading all data as a zip, I can still see these expressions in the expressions.json file.

**Comment by ckatta** [comment] 2018-02-13 04:28
@patapizza , [Wit api is returning 0 entities for trained expressions #964](Wit api is returning 0 entities for trained expressions #964) , am experiencing same issue.

**Comment by patapizza** [comment] 2018-02-13 15:23
@touchaponk For which entity did you do that? And which expressions?

@josephlingzb Same questions, and what is your app id?

@ckatta Addressing your issue in #964.

**Comment by l5t** [comment] 2018-02-13 17:12
for @josephlingzb it happens with all his apps, one example here: 59f6f0e3-2844-40d6-b9ee-599712584c67

**Comment by touchaponk** [comment] 2018-02-13 17:15
@patapizza I only have 1 entity inside the bot called "Intent" (trait)... and it happens to all expression, cant seem to detect anything

**Comment by josephlingzb** [comment] 2018-02-14 08:02
Just to add on, if I then go to the wit.ai console and add a new intent through the console, things start working again.

**Comment by patapizza** [comment] 2018-02-14 13:30
@josephlingzb Thanks for the additional information.

**Comment by patapizza** [comment] 2018-02-14 15:06
This is related to https://github.com/wit-ai/wit/issues/950. I'm working on it.

**Comment by recime-platform** [comment] 2018-02-14 21:07
I am getting similar behavior for this bot: 5a849ba6-e48d-451b-ba91-2ee76a18f16a. It is returing nothing, no matter what I type.

**Comment by patapizza** [comment] 2018-02-14 22:09
@recime-platform It seems like it's working:

![](https://i.imgur.com/6jLSLwJ.png)
![](https://i.imgur.com/seThB8K.png)

@josephlingzb Trying one of your apps seems working as well:

![](https://i.imgur.com/E4JWHGH.png)
![](https://i.imgur.com/4rxwtvB.png)

@touchaponk It seems like your apps still experience issues. Can you try refixing it through the console? `PUT https://api.wit.ai/entities/$ENTITY_ID` has been fixed.

**Comment by recime-platform** [comment] 2018-02-14 22:36
Working now

**Comment by touchaponk** [comment] 2018-02-14 22:38
@patapizza still experiencing the problem on 5a7bee9d-0140-4d21-9db6-6224e3afc5fb

**Comment by josephlingzb** [comment] 2018-02-15 00:41
Hi @patapizza,

The old intents are working. The problem arises when we use the PUT https://api.wit.ai/entities/$ENTITY_ID to add to update any intents. The new intents or even added expressions on old intents do not work until we use the wit.ai console to add a new intent and allow the model to retrain.

I just tested again, the problem still exists. To reproduce the problem, use the API to update the entity with a new intent. Then try to test and see if the expression can activate that intent.

**Comment by patapizza** [comment] 2018-02-15 18:20
Got it, still working on it.

**Comment by patapizza** [comment] 2018-02-17 01:30
A fix has been deployed. Can you guys try doing a `PUT /entities/intent` request, wait a few minutes and confirm things are going as expected?

Thank you for your patience.

**Comment by SoumyaChaudhuri** [comment] 2018-02-17 01:58
It's working for me now.  Thanks.

**Comment by josephlingzb** [comment] 2018-02-17 02:05
Its working for me too. Thanks!

**Comment by patapizza** [comment] 2018-02-18 05:01
Awesome, closing.

**Closed by patapizza** 2018-02-18 05:01 UTC
Labels: bug

**Comment by SoumyaChaudhuri** [comment] 2018-03-14 15:51
This appears to be happening again.

**Comment by josephlingzb** [comment] 2018-03-15 07:54
Yes I'm having the same issue again. Its pretty disruptive that this keeps occurring!

**Comment by patapizza** [comment] 2018-03-16 18:18
@josephlingzb It seems that this was a different, transient issue. Do you still experience the issue?

**Comment by josephlingzb** [comment] 2018-03-19 08:14
@patapizza yes we are still experiencing it. app id 5a336efc-05fb-4775-b180-5e8c2be881cf

**Comment by patapizza** [comment] 2018-03-19 15:37
@josephlingzb I've retrained your app and it seems to be working. Can you share examples/values that don't work? Thanks.

**Comment by CME64** [comment] 2019-08-01 11:57
if you're experiencing this right now, it's probably due to the training not being done actually. you man see a "scheduled" keyword showing you when the training will be applied. then you can run tests to see if it's working/make use of your training data.
