### ISSUE TITLE
Wit API - Receive 500 status_code on some messages, but not others

### ISSUE THREAD

**Issue by GreasyBacon** [wit-ai/wit#540] opened 2017-05-03 18:00 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Reporting a *bug*

**What is the current behavior?**

Depending on the message I'm sending to the Wit API, some responses will return a 500 status code with an error message, whereas others will respond with a processed message + entities. This has been occurring for approximately 2 days now. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Here's an example in my ipython terminal:

![message_url_and_header](https://cloud.githubusercontent.com/assets/5730803/25674367/2e4a1f40-3000-11e7-929e-242b0ac33b38.png)

![query_difference_wit_ai](https://cloud.githubusercontent.com/assets/5730803/25674474/87811866-3000-11e7-9913-bc9146dbcb26.png)

**What is the expected behavior?**

The message that is providing the 500 error in the screenshot example has worked in the past and would provide the following:
intent = search_events
entities.location = brooklyn
entities.datetime = tonight

**What is the App ID where you are experiencing this issue (if applicable)?**
App ID is: 587cf13d-732b-4d80-8951-5394fd021e5e

**Comment by stopachka** [comment] 2017-05-10 23:12
Hi @GreasyBacon this was most likely caused by an intermittent error. Do you still get this issue?

**Comment by GreasyBacon** [comment] 2017-05-11 01:19
Hi @stopachka, still getting this issue unfortunately. 

In the last 2 days we have created a new app (id - 59121fd7-c46f-460e-82b0-9716df5d7659) and performed some training with it, and it is able to reply without an error code. 

![wit_error](https://cloud.githubusercontent.com/assets/5730803/25927637/e67e5812-35bc-11e7-88f9-6e0d36c8d172.png)
 
Could there be a specific issue with our app, rather than an intermittent error?

**Comment by l5t** [comment] 2018-12-20 23:15
Closing as this was likely fix by our work on reliability

**Closed by l5t** 2018-12-20 23:15 UTC
Labels: bug
