### ISSUE TITLE
wit crashed with  Bad Request

### ISSUE THREAD

**Issue by mohdnizamat** [wit-ai/wit#1111] opened 2018-06-09 06:09 UTC
{'object': 'page', 'entry': [{'id': '245599935571000', 'time': 1528524518675, 'messaging': [{'sender': {'id': '245599935571000'}, 'recipient': {'id': '1684120861686436'}, 'timestamp': 1528521856736, 'message': {'is_echo': True, 'app_id': 448419105608105, 'mid': 'mid.$cAACFrEn9eBVqFEXe4Fj4wCWKL_5P', 'seq': 44102, 'text': "Hebbal Darussalam: https://www.google.co.in/maps/dir/''/skssf+hostel/data=!4m5!4m4!1m0!1m2!1m1!1s0x3bae1784b9bb71f7:0xdbcffa0b85ffa6ae?sa=X&ved=0ahUKEwjNxr-968XbAhVEuI8KHfuTA1YQ9RcIwAEwEw  - \n Banashankari: https://www.google.co.in/maps/dir/''/SKSSF+HOSTEL+-+Banashankari,+9th+Main+Road,+Banashankari+Stage+II,+Banashankari,+Bengaluru,+Karnataka/@12.9173506,77.4988377,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3bae15792233e723:0xebbc5a08396504ec!2m2!1d77.5688782!2d12.9173599"}}]}]}
2018-06-09T06:08:39.299238+00:00 app[web.1]: [2018-06-09 06:08:39,298] ERROR in app: Exception on / [POST]
2018-06-09T06:08:39.299242+00:00 app[web.1]: Traceback (most recent call last):
2018-06-09T06:08:39.299244+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
2018-06-09T06:08:39.299245+00:00 app[web.1]:     response = self.full_dispatch_request()
2018-06-09T06:08:39.299247+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
2018-06-09T06:08:39.299248+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2018-06-09T06:08:39.299250+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
2018-06-09T06:08:39.299251+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2018-06-09T06:08:39.299252+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
2018-06-09T06:08:39.299254+00:00 app[web.1]:     raise value
2018-06-09T06:08:39.299255+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
2018-06-09T06:08:39.299256+00:00 app[web.1]:     rv = self.dispatch_request()
2018-06-09T06:08:39.299257+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
2018-06-09T06:08:39.299259+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2018-06-09T06:08:39.299260+00:00 app[web.1]:   File "/app/app.py", line 43, in webhook
2018-06-09T06:08:39.299261+00:00 app[web.1]:     entity = wit_response(messaging_text)
2018-06-09T06:08:39.299262+00:00 app[web.1]:   File "/app/utils.py", line 10, in wit_response
2018-06-09T06:08:39.299264+00:00 app[web.1]:     resp = client.message(message_text)
2018-06-09T06:08:39.299265+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wit/wit.py", line 68, in message
2018-06-09T06:08:39.299267+00:00 app[web.1]:     resp = req(self.logger, self.access_token, 'GET', '/message', params)
2018-06-09T06:08:39.299268+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wit/wit.py", line 41, in req
2018-06-09T06:08:39.299270+00:00 app[web.1]:     ' (' + rsp.reason + ')')
2018-06-09T06:08:39.299277+00:00 app[web.1]: wit.wit.WitError: Wit responded with status: 400 (Bad Request)

**Comment by stopachka** [comment] 2018-06-11 18:06
Hey @mohdnizamat -- could you give me a repro of the request that caused it? (either curl request or sample python code) would be great. This will help us find the root cause

**Comment by mohdnizamat** [comment] 2018-06-12 05:56
import os, sys
from flask import Flask, request
from utils import wit_response
from pymessenger import Bot

app = Flask(__name__)
PAGE="ID"
bot=Bot(PAGE)

@app.route('/', methods=['GET'])
def verify():
	# Webhook verification
    if request.args.get("hub.mode") == "subscribe" and request.args.get("hub.challenge"):
        if not request.args.get("hub.verify_token") == "hello":
            return "Verification token mismatch", 403
        return request.args["hub.challenge"], 200
    return "Hello world", 200

@app.route('/', methods=['POST'])
def webhook():
	data = request.get_json()
	log(data)
	if data['object'] == 'page':
		for entry in data['entry']:
			for messaging_event in entry['messaging']:

				# IDs
				sender_id = messaging_event['sender']['id']
				recipient_id = messaging_event['recipient']['id']

				if messaging_event.get('message'):
					# Extracting text message
					if 'text' in messaging_event['message']:
						messaging_text = messaging_event['message']['text']
					else:
						messaging_text = 'no text'
					
					response = messaging_text
					#categories = wit_response(messaging_text)
					#elements = get_news_elements(categories)
					bot.send_text_message(sender_id, response)
	return "ok",200

def log(message):
	print(message)
	sys.stdout.flush()

if __name__ == "__main__":
	app.run(debug = True, port = 80)

This is the python code, it is staright forward.

**Comment by stopachka** [comment] 2018-06-20 07:54
closing for now, feel free to re-open with the repro

**Closed by stopachka** 2018-06-20 07:54 UTC
