### ISSUE TITLE
Content no longer available UI Error

### ISSUE THREAD

**Issue by SecondThread** [wit-ai/wit#1807] opened 2020-06-14 19:43 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
In the "Train Your App" section, clicking the down arrow next to one of the suggestions gives a UI popup saying "This content is no longer available":
![image](https://user-images.githubusercontent.com/18317476/84602442-77961880-ae55-11ea-9000-fe1d09e7de36.png)

This makes training annoying

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
go to https://wit.ai/v2/apps/247699802991704/understanding
and click the down arrow next to one of the train your app lines.

**What is the expected behavior?**
no annoying dialog plz

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
247699802991704 I think. Also, that's kind of rude to say that if we don't give you the app id to log in as us that you can't debug your own website, but okay...

**Comment by TRPostma** [comment] 2020-06-15 10:00
I'm having the same annoying problem, subscribing to this issue.

**Comment by jtliao** [comment] 2020-06-15 16:07
Sorry about that, we're working on the problem. 

(And the template is not intended to be rude, far too often people post issues with no information on how to reproduce it. So having that there helps us help you.)

**Comment by jtliao** [comment] 2020-06-16 00:31
This should be fixed now.

**Closed as completed by jtliao** 2020-06-16 00:31 UTC
Labels: bug
