### ISSUE TITLE
Invalid intent detection plus messing up with the understanding [Huge issue]

### ISSUE THREAD

**Issue by mahieddine** [wit-ai/wit#214] opened 2016-04-24 14:43 UTC
Hi,
Since the last wit update, wit.ai is very unstable 
* When you create a new story 
       1 - Wit.ai detects wrong intent (that's ok i can correct it) the problem is that it modifies accordingly my intents and add values in the wrong entities, add expressions in the wrong entities too why ?
       2 - Wit.ai updates directly my entities based on user inputs, this is a big  issue
       3 - For some stories wit.ai tell me that "wit couldn't find this entity" of course this entity exists but somehow it raises this error

* It seems to me unacceptable that wit breaks stories just like that between each upgrade, this is the second time, we can't deal with this in prod app

**Comment by blandinw** [comment] 2016-04-26 20:41
We apologize for the very bad experience 😞
Thanks for the feedback. We've experienced exceptionally bad issues with our infrastructure over the weekend, which is probably the cause of your frustration.

1) This may be due to issues mentioned above. I'll look at your app and try to reproduce.
2) Entity values are added as you _validate_ expressions, this has always been the case. What behavior did you expect instead?
3) This error message is confusing, you're right. Fixing it is on the roadmap.

Being backwards-compatible is one of our priorities. I'm looking into 1)

**Comment by blandinw** [comment] 2016-04-26 21:04
@mahieddine I looked at your apps and everything seems to be working fine.
Please let me know if I missed anything. The issues were probably not related to our upgrade, but to our transient failures over the weekend. Sorry for the inconvenience. Closing now.

**Closed by blandinw** 2016-04-26 21:04 UTC

**Comment by mahieddine** [comment] 2016-04-28 14:36
hi @blandinw  everything is working great now ! i think it is related to infra failures for sure. thank you
