### ISSUE TITLE
Russian speech recognition problems

### ISSUE THREAD

**Issue by Phoenix1833** [wit-ai/wit#2432] opened 2022-05-14 10:02 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG
**What is the current behavior?**
Does not recognize single short words, for example, a word "yes". Began May 13, 2022
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The attached file on the Russian model returns an empty answer

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2250282511767645

[in.wav.zip](https://github.com/wit-ai/wit/files/8692671/in.wav.zip)

**Comment by bkroekr** [comment] 2022-05-19 18:12
We have reproduced the issue and are working on a solution.

**Comment by Phoenix1833** [comment] 2022-05-26 14:25
Hello. Any news?

**Comment by Barbog** [comment] 2023-04-18 09:40
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.

**Closed as not planned by Barbog** 2023-04-18 09:40 UTC
