### ISSUE TITLE
Issue with Intent Name

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2466] opened 2022-06-15 09:44 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
After changing intents names, the old name is returned in the 'message' API response.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Send 'القائمة الرئيسية'.

Old intent name: MainMenu
New intent name: main_menu_ar

When fetching the intents, the new name is returned:
![image](https://user-images.githubusercontent.com/99329638/173797196-1b04768e-2d5d-40f8-bba7-27958ee50b7b.png)

But in the 'message' API response, the old name is returned:
![image](https://user-images.githubusercontent.com/99329638/173797371-17ed6106-4be7-4558-bc94-abffa8d32eac.png)

**What is the expected behavior?**
The changes on the intents names to be reflected on the 'message' API response.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2496046537376221

**Comment by wangzhenict** [comment] 2022-06-16 20:55
Hi @aya-labiba , can you check if the issue is still there? if yes, can you paste the whole url you are using in the tool, I'll try from my side and debug it.

**Comment by aya-labiba** [comment] 2022-06-19 06:19
Hi @wangzhenict, please find the URL below:

https://api.wit.ai/message?q=القائمة الرئيسية&n=8&v=20190904

The issue is not there now, because I deleted the intent and added a new one with the new name

**Comment by Barbog** [comment] 2023-04-18 09:44
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.

**Closed as not planned by Barbog** 2023-04-18 09:44 UTC
