### ISSUE TITLE
Priorizar entidades

### ISSUE THREAD

**Issue by AlexisNichel** [wit-ai/wit#707] opened 2017-08-09 15:53 UTC
Hay alguna manera de priorizar las entidades.
Suponiendo que tengo la siguiente frase:
Numero de telefono de Juan.
y suponiendo que tanto número como teléfono corresponden a una misma entidad el resultado sería el siguiente:
{
"msg_id": "xxxxxxxxxxxxxxxxxxxxxxx",
"_text": "Numero de telefono de Juan.",
"entities": {
"solicitud": [
{
"confidence": 1,
"value": "numero",
"type": "value"
},
{
"confidence": 0.99354678522225,
"value": "telefono",
"type": "value"
}
]
}
}
Hay forma de priorizarlo?? para que en el Json primero me devuelva telefono y luego numero..
Éste es un simple ejemplo, no es el caso real de uso.

**Comment by stopachka** [comment] 2017-08-10 22:56
Hey @AlexisNichel 

(I tried to translate xD) 

--- 

What I understand is, you have a problem when  there is a number and a phone number entity. What do you mean by prioritize? 

What is the expected behavior you want, and what is the current one?

**Comment by blandinw** [comment] 2017-08-10 22:56
Hi @AlexisNichel, thanks for your feedback.

Please use English when posting issues because we do not speak Spanish :).
I'm not 100% sure what you're asking, but your example does not seem to make much sense.
You can use roles to differentiate 2 instances of the same entity in the sentence: https://wit.ai/docs/recipes#differentiate-several-entities-according-to-their-role-in-the-message

You cannot manually sort entities in the "solicitud" array (if that's what you mean by priorizar)

Closing until we have more info.

**Closed** 2017-08-10 22:56 UTC
Labels: need-more-info
