### ISSUE TITLE
Not able to uttarence

### ISSUE THREAD

**Issue by surajsingh92** [wit-ai/wit#1921] opened 2020-09-21 10:38 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
ask a question
**What is the current behavior?**
I am posting the below data in sample API.

[{
       "text": "What is the response rate for tomorrow",
       "entities": [
          {
            "entity": "intent",
            "value": "response_get"
          },
          {
             "entity": "wit$datetime",
            "value": "tomorrow",
            "start":30,
            "end":38
          }          
        ]
      }]

when I post this data first time then it creates the utterance successfully and create the entity DateTime in the entity section.  After that, I deleted that utterance but not deleted the DateTime entity and after that when I try to create an utterance then it's not created. If  I have already an inbuilt DateTime entity and when I tried to create any utterance with date-time entity then it will not work.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
324212385527094

**Comment by patapizza** [comment] 2020-09-22 22:45
Duplicate of https://github.com/wit-ai/wit/issues/1917. `wit$datetime:datetime`.

**Closed as completed by patapizza** 2020-09-22 22:45 UTC
