### ISSUE TITLE
Error on utterance tab (Error: Something went wrong. We've been notified)

### ISSUE THREAD

**Issue by aggeus2014** [wit-ai/wit#2503] opened 2022-08-08 05:56 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**
for now, we are experiencing that if we train a keyword or utterance to match an intent after the training it will return a different intent or fall to others even if the entity keyword is pointing to the correct entity and that is included on the intent, also the utterance tab is not working on our app. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/6658602/183348425-58d12209-a80c-4cde-ba15-131d5846bfec.png)
![image](https://user-images.githubusercontent.com/6658602/183348913-98ad9a49-8889-4634-9ff7-ed65ecf50c79.png)

**What is the expected behavior?**
the tab will show the utterances and after the training, it should return the intent for a certain entity.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
994708554407758

**Comment by yolanother** [comment] 2022-08-14 17:43
@aggeus2014 is this still an issue for you?

**Comment by aggeus2014** [comment] 2022-08-15 04:17
@yolanother yes

**Comment by wangzhenict** [comment] 2022-08-19 01:06
Hi @aggeus2014 , I tried a fix on it. it seems already fixed, can you check it from your side?

**Comment by wangzhenict** [comment] 2022-08-19 18:51
the issue is fixed. I'm closing the issue and please reopen it if you still see problem. thanks

**Closed as completed by wangzhenict** 2022-08-19 18:51 UTC
