### ISSUE TITLE
404 - Unable to access wit.ai app. Homepage not found

### ISSUE THREAD

**Issue by Nyxter** [wit-ai/wit#1100] opened 2018-05-31 16:16 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
404 and a message 'What you were looking for could not be found' on my apps homepage
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To recreate:

- Go to my homepage,
- Click the app name to go to the app page
- 404 appears

**What is the expected behavior?**
I expect to see the homepage of my wit.ai app

**What is the App ID where you are experiencing this issue (if applicable)?**
Unable to provide it due to page app failing & so unable to get to homepage

**Comment by l5t** [comment] 2018-05-31 17:14
Thanks for posting. We are investigating

**Comment by stopachka** [comment] 2018-05-31 21:12
Hey @Nyxter I have mitigated and brought the app back alive. I am investigating further into the root cause and what the issues are. 

Question for you: 

As I look into the app, I noticed that all the parsers have been deleted before. Could you go in a bit more detail in the action steps you took before the error happened, and if the parser deletes were intentional? Would love to get to the bottom of this

**Comment by Nyxter** [comment] 2018-06-01 08:16
Thanks for doing that.

We are deleting the expressions (if this is what you meant by parsers).

Upon releasing our messenger bot, we fully re-train the wit.ai application.

The steps we take are:
- Get all expressions already in system
- Delete all expressions
- Re-send all new expressions 

The reasons for the delete is that some of the entities or intents may have had slight lexical changes, so we re-send all the latest expressions to ensure highest accuracy for each entities and intent. Without the delete it would be an additive process..

Let me know if I can be of any further help.

**Comment by aforaleka** [comment] 2018-06-01 21:21
Thanks for the info @Nyxter! :) Closing the issue since the app is back -- but we will continue to investigate the issue and prevent it from happening in the future.

**Comment by stopachka** [comment] 2018-06-02 19:18
Let's use this as the main project to track the root cause of the issue. Once we fix it, we can remove it

**Closed** 2018-12-18 19:36 UTC
Labels: bug
