### ISSUE TITLE
error "wit the hell" on /converse API

### ISSUE THREAD

**Issue by sindre** [wit-ai/wit#710] opened 2017-08-10 11:37 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
in the last hour, sending the first request (with a message) to the converse API responses with 
body: "wit the hell?"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
No error

**What is the App ID where you are experiencing this issue (if applicable)?**
573c7652-5ac4-4a83-96d2-d81d7d79a239

**Comment by blandinw** [comment] 2017-08-10 18:27
Looking

**Comment by sindre** [comment] 2017-08-10 18:36
working again.

**Comment by blandinw** [comment] 2017-08-10 18:51
@sindre I'm still investigating to understand what happened and make sure it does not happen again.
Was your app 100% unusable during that time period? How long was this?

**Comment by sindre** [comment] 2017-08-11 09:17
the first error occurred at Aug 10 12:18:05 CET with:
https://api.wit.ai/converse?session_id=2017-08-10T10%3A17%3A34.343Z&q=USER_DEFINED_PAYLOAD

the last error at Aug 10 13:27:51 CET with:
https://api.wit.ai/converse?session_id=2017-08-10T11%3A26%3A36.024Z&q=USER_DEFINED_PAYLOAD

in between every request was responded with "wit the hell?"- so  the bot was completely unusable during that time period

in the last 12 hours we had about 6 single similar errors events.

**Comment by blandinw** [comment] 2017-08-11 17:09
@sindre Receiving "wit the hell?" (with I assume status 404) is very surprising.
I want to make sure your app works as expected, so could you add me on Messenger (search for my name) and send me in private some logs that actually triggered the error?

**Comment by sindre** [comment] 2017-08-12 18:48
sent you an Message on FB Messanger. Maybe it has something todo with "max steps".

**Comment by blandinw** [comment] 2017-09-05 18:08
We did a few fixes related to this issue + no other user report.
Closing, feel free to comment/reopen

**Closed by blandinw** 2017-09-05 18:08 UTC
Labels: bug, investigating

**Comment by richwednesday** [comment] 2018-01-15 11:48
Currently having this issue for this endpoint https://api.wit.ai/samples

{ body: 'wit the hell?' }

**Comment by stopachka** [comment] 2018-01-15 13:25
Hey @richwednesday 

Please open an issue, and include:
- Your app id
- When you sent requests, and if it is consistently happening
- An example request (leave you your access token)

This way we can look further to see what the cause would be
