### ISSUE TITLE
Bad auth, check token/params on creating new app via api

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2233] opened 2021-10-28 09:54 UTC
Hi,

As per the issue #2083, we have create a dummy app and are using its token for creating app sin wit via api. But when we tried today with the same token it showed the below error
 info: { status: 400, info: 'Bad auth, check token/params' }
When we tried with another token it worked.

No apis with the old token are working.
We encountered the same issues with some other wit apps also.

Can anyone please confirm if there is any limit for creating an app using same token.

Thanks

**Comment by b-tix** [comment] 2021-10-28 11:17
Hi all! Same to us. App-ID 2115985458480186. `Bad auth, check token/params" code: "no-auth"`

**Comment by anjaly** [comment] 2021-10-29 03:16
Hi all. Any updates. None of the wit apps are working. All showing the Bad auth, check token/params error

**Comment by SisikHBS** [comment] 2021-10-29 06:16
Same here getting error creating apps with initial API.

**Comment by admin-pulsar** [comment] 2021-10-29 07:19
Hello, We have the same problem, App ID is 1450216708378959, getting error:  Bad auth, check token/params" code: "no-auth"

**Comment by lycai-fb** [comment] 2021-10-29 16:40
Thanks for the reports. We're investigating the issue.

**Comment by SisikHBS** [comment] 2021-10-29 17:25
I completely deleted the account and opened new account. New account keys does not have the problem.

**Comment by anjaly** [comment] 2021-11-01 00:30
Thanks  @lycai-fb 
We are unable to login to our wit account now. Can you please check.

**Comment by lycai-fb** [comment] 2021-11-02 00:13
Going to mark this as a duplicate of #2234 since we have more activity there.

**Closed as completed by lycai-fb** 2021-11-02 00:13 UTC
