### ISSUE TITLE
out of scope preselected 

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#1852] opened 2020-07-23 08:04 UTC
hi,

In the  understanding section of the new interface, "out of scope" comes preselected for all answers. Could you help us correct that? we don't want it to be selected for any reply.

app id: 2841817995840539

<img width="1128" alt="wit" src="https://user-images.githubusercontent.com/48153186/88265054-76b69900-ccd5-11ea-9e45-5f56628fde5b.png">

thanks

**Comment by jtliao** [comment] 2020-07-23 20:58
This is not a bug -- we run the utterance against your apps models when showing it in the inbox. If it shows up as out of scope, it means that's what your app would have predicted, otherwise there would be intents/entities that show up there.

**Closed as completed by jtliao** 2020-07-23 20:58 UTC
