### ISSUE TITLE
Unable to export app data

### ISSUE THREAD

**Issue by akshayraghunath** [wit-ai/wit#2279] opened 2021-12-22 07:10 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
When the "Download .zip with your data" button is clicked under app settings, getting an error message "Something went wrong. We've been notified."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Go to the Wit app > Management > Settings > Click on the "Download .zip with your data" button

**What is the expected behavior?**
The Zip file with the data must be downloaded

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 1497612310349057

**Comment by wangzhenict** [comment] 2021-12-22 20:27
Hi friend, 
I'm investigating it. will get back to you soon. thanks for your patience.

**Comment by akshayraghunath** [comment] 2021-12-24 04:48
Hi buddy - Any update on the above?

**Comment by wangzhenict** [comment] 2021-12-24 05:30
Hi @akshayraghunath, 
I tried this app, and met some permission check issue. it looks I need your help to add me to your app's contributor. you can do it through app > management > settings > contributors, my user name is 'zhenwang',
then i will debug further, you can remove me after the issue is addressed.

If you feel ok for that, just let me know once you added me.

Thanks,

**Comment by akshayraghunath** [comment] 2021-12-24 06:10
@jtliao @patapizza @ramh I have seen many similar issues reported. Could you please help?

**Comment by Barbog** [comment] 2023-04-18 09:38
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.

**Closed as not planned by Barbog** 2023-04-18 09:38 UTC
