### ISSUE TITLE
High confidence for incorrect utterances

### ISSUE THREAD

**Issue by CannonFodderr** [wit-ai/wit#2386] opened 2022-03-06 07:47 UTC
Wit agent returns utterances attached to the wrong intents with confidence higher then 0.92 as well as out of scope utterances.

App ids:
1134614730693614
321292556446914

We see this issue more and more with newly created apps, we can also confirm it happens with English, Chinese and Thai languages.
Retraining the app sometimes resolves the issue but in some cases (Like the apps above) it does not.

**Comment by doggeral** [comment] 2022-03-06 08:08
@CannonFodderr 
> newly created apps

I believe these new apps are imported from the previous saved app files. We upgraded the model architecture and training infra, if you need to build new app, please create from scratch instead of importing from app file.

**Comment by CannonFodderr** [comment] 2022-03-06 19:47
They are not imported, they are created via api requests.
Also, We tried to open a new wit account and create few apps, issues was easily reproduced. Once few apps are created we experience 500 errors for some apps and for some we get high confidence for out of scope utterances.

For instance app id: 3130448873938618 (Created today with api calls)
It has "Hello world" as out of scope and one intent with one utterance.
If I submit "Hello world" as a message I get this response back:

`{
    "text": "Hello world",
    "intents": [
        {
            "id": "1338296480015061",
            "name": "cats_intent",
            "confidence": 0.9951
        }
    ],
    "entities": {},
    "traits": {}
}`

We also get high confidence for messages which were never submitted as utterances to the app and 500 errors from time to time.
We were able to reproduce this in many apps in 2 separate accounts with multiple languages. (Mostly English, Chinese, Japanese and Thai).

I attach few responses we got with some examples of Thai and English apps. In these apps intent is about cats, and Hello world is sent to be out of scope. (Same in both languages).
![thai out of scope](https://user-images.githubusercontent.com/36086310/156939788-953ea7c2-c32c-48f9-9cba-f09e0e7ea5b9.PNG)
![Thai](https://user-images.githubusercontent.com/36086310/156939803-f13c0b99-f707-493d-a5a2-fa304bc7d4a9.PNG)
![Thai3](https://user-images.githubusercontent.com/36086310/156939817-62655774-e023-4e4e-af47-9ecbf9ae35f9.PNG)
![Thai4](https://user-images.githubusercontent.com/36086310/156939822-f20926f0-d126-4793-8927-d7311ea3025e.PNG)
![EN OUT OF SCOPE](https://user-images.githubusercontent.com/36086310/156939836-e8657080-6aab-4fbc-8894-9dd4163ef357.PNG)
![EN1](https://user-images.githubusercontent.com/36086310/156939837-1c92a5c8-2dd6-41a4-8690-ab8e6814bf41.PNG)

**Comment by doggeral** [comment] 2022-03-06 21:11
> For instance app id: 3130448873938618 (Created today with api calls)

Per the backend meta data, the app uses the deprecated model architecture, that's why your app encountered the intent issue. Same issue for 1134614730693614. Could you elaborate how you create these apps?

**Comment by CannonFodderr** [comment] 2022-03-06 22:52
@doggeral 
I follow the wit documentation with creating the app: https://wit.ai/docs/http/20210928/#post__apps_link
Just a post request, you can see the code in this gist: https://gist.github.com/CannonFodderr/1ef622b5f3344e80f3b412ad24d766d9

**Comment by CannonFodderr** [comment] 2022-03-07 07:17
Btw, Because we started seeing this issue pop up when we had a lot of accounts we opened a new account for testing, these issues did not appear if we had 10 apps in the account but once we created over 200 apps issues started appearing in the testing account. We have many apps in the real production account suffering from this.

**Comment by doggeral** [comment] 2022-03-07 07:23
@CannonFodderr could you help to share the app suffering from the issue in production with example request/response?

**Comment by CannonFodderr** [comment] 2022-03-07 07:27
@doggeral We have many apps like this I will prepare a few app ids with request / response for you but I am wondering if the is a global fix that might be applied ?

**Comment by CannonFodderr** [comment] 2022-03-07 09:04
Here are some production apps examples:

APP ID: 721836905469803 Language Japanese:
1. **"Hello world" is out of scope but returns a match to intent**
![out of scope response](https://user-images.githubusercontent.com/36086310/156999346-d3055f0e-1499-4388-98d3-3f4a139f4c17.PNG)
![out of scope](https://user-images.githubusercontent.com/36086310/156999349-74ce642c-9d12-452d-8220-2601e0407757.PNG)
2. **Out of scope utterance in the same language as app returns attached to intent**
![Out of scope in same language return attached to intent](https://user-images.githubusercontent.com/36086310/157000495-66cc398a-46b0-4da4-b600-a8f251259b07.PNG)
![Out of scope in same language return attached to intent response](https://user-images.githubusercontent.com/36086310/157000506-a9d65ac6-8150-410c-83a5-34ee694ba41b.PNG)

3. **"Test" is not in app utterances still returns with confidence to intent**
![No existing utterance](https://user-images.githubusercontent.com/36086310/156999436-ed45abd5-b3fa-496a-99ca-25462062f35a.PNG)
4. **Utterance attached to intent returns as "out of scope"**
![utterance attached to intent return as out of scope](https://user-images.githubusercontent.com/36086310/156999841-2bc7dffe-fbdc-41d4-bd8e-928ad84ac3a8.PNG)
![utterance attached to intent return as out of scope response](https://user-images.githubusercontent.com/36086310/156999963-872855e5-f4d9-49ff-a5a2-19514ed32328.PNG)

I will provide another examples of different apps languages apps soon

**Comment by CannonFodderr** [comment] 2022-03-07 10:05
Another example in English app id: 953376005551498
1. "Hello world" is out of scope but returns a match to intent
![out of scope](https://user-images.githubusercontent.com/36086310/157009557-e12a13a0-77eb-45ef-a45f-480f1aa9c956.PNG)
![out of scope response](https://user-images.githubusercontent.com/36086310/157009580-5330af27-7626-4b12-809e-1a585f436c72.PNG)
2. "Test" is not in app utterances still returns with confidence to intent
![not in app message](https://user-images.githubusercontent.com/36086310/157009754-5718af13-2f23-4af5-a49c-84175b5f3900.PNG)
3.Another example for message which does not exist in the app utterance pool
![not in app message2](https://user-images.githubusercontent.com/36086310/157010163-1fa461e3-ca9a-4396-855e-f4b648bcbbfe.PNG)
4. Momentary dashboard error, this appeared for a minute and then disappeared
![error](https://user-images.githubusercontent.com/36086310/157010291-1707dadb-8666-4fa6-b7ed-bbd3d61c6043.PNG)

**Comment by CannonFodderr** [comment] 2022-03-07 10:20
English App id: 683291973090104 - new app created today
Similar issues as in previous apps above:

1. "Hello world" is out of scope but returns a match to intent
2. "Test" is not in app utterances still returns with confidence to intent
3. Training took a long time for just 2 utterances, in this time we got 500 errors back from the api

**Comment by doggeral** [comment] 2022-03-07 17:29
@CannonFodderr Thanks for preparing the examples. Checked the data from our backend, the 683291973090104 953376005551498 uses the old model architecture, that's why the performance is low. I've migrated model for the two apps to new model architecture, the issue mentioned in your post should be fixed. We're investigating the root cause of creation issue.

**Comment by CannonFodderr** [comment] 2022-03-07 17:38
@doggeral 
It is weird because as I said 683291973090104 was an app we created today for testing, shy does it open on the old model instead of the new one? How can we be sure new apps use the new model ?

Is it possible to check which apps are old model in a user account and migrate them all? These are just 2 out of multiple apps experiencing the issues

We also see these come up with new apps we create in our testing account

Also what about 721836905469803 I submitted in the examples above ? it has the same issue ?

**Comment by CannonFodderr** [comment] 2022-03-08 16:23
@doggeral We are having those issues for one month now. 
Our company and product is utilizing your service to expose to 1000s of users around the world solutions in many different sectors.  
Those users are greatly relying on your service and now are experiencing big disruptions. 
For us, it is really easy to reproduce the problem with every new application created, from our production and development accounts. We are really considering our options now and hope you will be able to solve this ASAP

**Comment by doggeral** [comment] 2022-03-08 17:26
@CannonFodderr the issue has been fixed from our side. For the next step, could you
1. create a new app to verify if it works?
2. for the existing apps, could you share with me the app ids with production issue, I can help you to do the migrate.

**Comment by benjo0010** [comment] 2022-03-08 20:50
@doggeral So, for creating new apps, those are our observations:  while an app that has been created via the dashboard is functioning well, an app that has been created via API call is not functioning well and providing the same bad results we have been experiencing in the past month.  Those are the details

**1. Good app id** - 4984197714995950 - created from your dashboard.  Behaves well, as expected
**2. Bad app id**  - 532545664850753 -  created via API call. Providing the same bad performances results. 
**3. Our admin app id** - 1189127508177168



**The API  request for creating an app that always provides bad results** 

 :curl --location --request POST 'https://api.wit.ai/apps' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer (our admin token)
--data-raw '{
    "name": "clientapp3",
    "lang": "en",
    "private": true
}'

**The API response**
{
    "app_id": "53ecf19d-ac95-44e6-b67b-5a3b9158b821",
    "access_token": "our access token"
}

**Comment by CannonFodderr** [comment] 2022-03-09 17:52
@doggeral As my colleague @benjo0010  state above, we are now able to get good results with apps that were created from the wit dashboard.

But Whenever creating apps wit api requests we expirience the same malfunctions.

Please see the details he share before.
We tried it today with multiple apps

**Comment by doggeral** [comment] 2022-03-11 00:37
@CannonFodderr could you share some app ids you created today with prediction issues?

**Comment by CannonFodderr** [comment] 2022-03-11 10:01
@doggeral here are some apps I created today with API requests, all have prediction issues

492567715764777 - English
490294669401798 - Chinese
254640300200131 - Japanese

BTW, it is also very distinct that apps with issues like that: 
1. After app is created and completed the first training the first message request  takes considerably more time to respond and **always** respond with 500 error.
2. After 1 or 2 500 responses they will always return wrong intent for out of scope utterances
3. They have a very long training.

All of the above does not happen created from the dashboard and not with API requests.

**Comment by CannonFodderr** [comment] 2022-03-14 10:38
@doggeral Any update regarding this issue ?

**Comment by doggeral** [comment] 2022-03-17 06:05
@CannonFodderr we're working on the fix now. Sorry for the late reply.

**Comment by CannonFodderr** [comment] 2022-03-18 01:19
Thanks @doggeral  please let me know if there is an estimation to when this issue may be fixed.

**Comment by doggeral** [comment] 2022-03-21 16:55
@doggeral could you help to create the app via API to verify if the issue has been fixed?

**Comment by CannonFodderr** [comment] 2022-03-22 16:08
We ran several test on multiple apps in multiple languages and could not reproduce the issue 🥳

Does the fix apply also for already existing apps which are malfunctioning? Ones that were created during the issue period?

**Comment by doggeral** [comment] 2022-03-22 16:51
@CannonFodderr Thanks for the confirmation! Unfortunately it can't apply the existing apps, but you can provide the app list, I can help you to do the migration. Feel free to paste your affect app in another issue.
Close the issue.

**Closed as completed by doggeral** 2022-03-22 16:51 UTC
Labels: bug
