### ISSUE TITLE
Speech recognition null response

### ISSUE THREAD

**Issue by harmydiano** [wit-ai/wit#1551] opened 2019-09-23 14:15 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
The post responses are returning null
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
i get a null repsonse from the wit.ai server
**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2354525851234581

**Comment by patapizza** [comment] 2019-09-23 15:22
Thanks for reporting - duplicate of https://github.com/wit-ai/wit/issues/1550.

**Closed by patapizza** 2019-09-23 15:22 UTC
