### ISSUE TITLE
Cannot validate or delete expressions in my Inbox

### ISSUE THREAD

**Issue by joshuacrowley** [wit-ai/wit#551] opened 2017-05-10 05:58 UTC
**bug**

Trying to validate some of my expressions here -> https://wit.ai/joshuacrowley/Jiro/inbox/semantic

When I click validate, they disappear and then return after a second.

Console log returns: PUT https://api.wit.ai/sync?verbose=true 500 (Internal Server Error)

I cannot delete them either. I think these expressions could be months old.

**Comment by stopachka** [comment] 2017-08-30 18:33
Hey @joshuacrowley, apologies this task fell through.

took a look, and the cause was due to an error we had with metadata on the entities. Pushed a fix, and now the validation is working.

**Closed by stopachka** 2017-08-30 18:33 UTC
Labels: bug

**Comment by vikitries** [comment] 2018-01-18 19:00
Problem still persists and can't delete or validate items in inbox?
Can anyone help?

**Comment by l5t** [comment] 2018-01-19 04:36
Which app are you experiencing this issue?
