### ISSUE TITLE
wit.ai suffering from inconsistent loading and inbox training failure

### ISSUE THREAD

**Issue by tguidon** [wit-ai/wit#429] opened 2017-03-21 14:38 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Wit.ai will not load on many occasions. I will try using wit.ai on multiple browsers until finally, seemingly by luck, it will load the main dashboard. Then I click on my app name, go to the training Inbox page, and encounter more issues. I parse through incoming messages, validating or trashing them, and they will appear to have been logged and complete. When I load in more messages, the same messages I just tagged load. This happens many times in a row until I give up training and just try again another day. Some days it seems to save my training and some days it seems to not want to listen. Any insight on this?
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use the wit.ai website.
**What is the expected behavior?**
The website to work.

**Comment by yegeniy** [comment] 2017-03-21 14:59
I'm seeing similar issues. Seems like there was some kind of degraded state. The API was unresponsive for a little while. The website is now loading, and the API is responsive; however, my "trait" entities are not detected. The free-text/keyword entities are still being matched, as is the `wit/datetime` entitity, but my custom `intent` entity is not being picked.

**Comment by blandinw** [comment] 2017-03-21 15:03
Closing as a duplicate of #402.
@yegeniy Please provide your app-id, this should not happen.

**Closed by blandinw** 2017-03-21 15:03 UTC
Labels: bug

**Comment by yegeniy** [comment] 2017-03-21 15:23
@blandinw one thing to note is I changed the default timezone to `UTC` from `America/Los Angeles`; otherwise, it's a raw restore.

**Comment by yegeniy** [comment] 2017-03-21 15:34
I have confirmed that the model has not been modified since January 25th.
So the restored app (with id `58d13d18-bbb4-4518-971e-4d750341d574`) generates the same `.zip` export as the actual app (with id `57ee9e5b-ddec-485e-9bc8-2b4359d8675f`).

**Comment by blandinw** [comment] 2017-03-21 17:18
@yegeniy I looked at your apps and noticed that the `intent` entity has only 3 samples in both of them, whereas there exist samples like "How did the Mets do yesterday?" without any intent set (which, to Wit, is the same understands as saying "there's definitely no intent in this sentence").
Wit then tries to learn that "How did the Mets do yesterday?" should not return any intent, and only the samples tagged with the "intent" entity should return one.

This is expected, albeit confusing, behavior.

**Comment by yegeniy** [comment] 2017-03-21 17:54
Makes sense. I can train it properly then.

It was working up through yesterday with just those 3 positive samples, so
we stopped the training. I'll get it cleaned up. Thanks
