### ISSUE TITLE
Delays between 'converse' POST request to response

### ISSUE THREAD

**Issue by tefrati** [wit-ai/wit#317] opened 2016-09-12 16:42 UTC
Hi,

Lately, I've started to see delays of up to 15 seconds when sending a POST request to 'converse' with text.
I didn't notice this previously. Any idea what could be causing it?

Thanks,
Tzahi

**Comment by l5t** [comment] 2016-09-12 23:08
Thanks for reporting Tzahi. We also noticed this a few days ago but pushed a fix on Sept 8th. Are you still experiencing long response time?

**Comment by tefrati** [comment] 2016-09-13 00:25
Yes, I experienced it several times today:

- [2016-09-12T16:27:35.271Z] [wit][debug] POST https://api.wit.ai/converse?session_id=2016-09-10T13%3A54%3A20.317Z - 1 minute delay in response

- [2016-09-12T16:28:51.613Z] [wit][debug] POST https://api.wit.ai/converse?session_id=2016-09-12T16%3A28%3A51.613Z&q=What%20does% - 12 seconds delay

- [2016-09-12T16:29:14.705Z] [wit][debug] POST https://api.wit.ai/converse?session_id=2016-09-12T16%3A28%3A51.613Z&q=conact%20zach - 18 seconds delay

**Comment by thakurdDev** [comment] 2016-09-22 12:27
Hi, 
I m using wit.ai in my IOS app. and response is taking up to 15 seconds after send request.
Any idea what could be causing it?

**Comment by mahieddine** [comment] 2016-09-22 18:32
Hi,
I reported this issue long time ago #309 and the problem is still here, we often have request that takes 20seconds+ to process or wit errors 
Why is this happening ?

**Comment by swapniljain9667** [comment] 2016-09-23 19:06
I am also experiencing the same problem. Delay is too much.

**Comment by kaerusdev** [comment] 2016-10-06 04:47
+1

**Comment by l5t** [comment] 2018-01-22 01:31
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories

**Closed by l5t** 2018-01-22 01:31 UTC
