### ISSUE TITLE
Training wit slow and causes downtime

### ISSUE THREAD

**Issue by touchaponk** [wit-ai/wit#1060] opened 2018-04-19 04:04 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Training new intents now causes the instance to temporarily goes down (fail to classify any message). The usual behaviour used to be that the system will continue to use the old model until the new one is trained. Training time is also now much longer - increased from 1-2 minutes to 15-20 minutes

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Train the instance with a new set of data - the system will fail to classify any intent for several minutes.

**What is the expected behavior?**
The usual behaviour used to be that the system will continue to use the old model until the new one is trained.

**What is the App ID where you are experiencing this issue (if applicable)?**
5aaf36ba-79ee-47a5-aa2f-2e5c330c90ee
59c9dd5a-84b5-44e8-a196-07b3ea4c9a34
and many more

**Comment by blandinw** [comment] 2018-04-24 19:54
@touchaponk I cannot reproduce your issue. We only replace the old model once the new one is trained. The app ending in `2e5c330c90ee` was working fine during training.
What do you mean by "instance goes down"? What is the exact symptom you're seeing?

Regarding training being longer, we're experiencing intermittent slow down in training that we're working on fixing.

Closing for now, feel free to comment with more information (better error message/symptoms, consistent repro steps)

@vnheros I don't understand your message. We train a new model when you provide new sentences. The old model will be used until the new model is available. We cannot use the new model if it does not exist yet.

**Closed by blandinw** 2018-04-24 19:54 UTC
Labels: investigating
