### ISSUE TITLE
Cannot train app!! / Utterances not appearing in Understanding tab

### ISSUE THREAD

**Issue by nickcbarone** [wit-ai/wit#2566] opened 2022-12-03 22:26 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I don't see any utterances available to train even though there should be hundreds

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Navigate to the app's Understanding page
2. Look at the blue button to see if there is data available to train

**What is the expected behavior?**
You should see hundreds of utterances available to train. Instead, I see "No data"

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1650554041800318
<img width="1049" alt="Screen Shot 2022-12-03 at 2 24 54 PM" src="https://user-images.githubusercontent.com/11508524/205464578-d6e5e430-c112-45d9-9f64-14bd6dace788.png">

**Comment by nickcbarone** [comment] 2022-12-06 17:01
Hello, can someone please help me with this problem??

**Comment by yuzh174** [comment] 2022-12-06 17:42
Thanks for reporting. I am looking into this

**Comment by yuzh174** [comment] 2022-12-06 23:53
I found the cause why the data doesn't show up. You have some pretty long requests that exceed our character limit (1024). They are HTML code blocks. In case that's not intentional, you may want to filter the messages sent, as HTML blocks won't be processed anyone. 

At the same time, I am working on a fix so the long text message won't block your Understanding page usage.

**Comment by nickcbarone** [comment] 2022-12-06 23:55
Ahh that's really helpful to know! Thank you so much for helping with this. We sometimes get hit by spam emails that are really long. It might be hard for us to filter those out though. Would you be able to filter them on your end so that it doesn't break the Understanding page?

**Comment by yuzh174** [comment] 2022-12-07 01:57
Sure, that's what I am working on. We will filter them out from the Understanding page. 
I asked just in case you didn't know the long text sent. If that's the normal usage of your app, that should fine. We can filter them.

**Comment by nickcbarone** [comment] 2022-12-07 16:34
Ok thank you so much. Yes, that is normal usage for our app.

**Comment by yuzh174** [comment] 2022-12-07 22:32
@nickcbarone the issue should be fixed now. It may take a few hours to fully deploy. Let us know after that if you still experience the problem after a few hours. 

Also I noticed that you are using the new design of the understanding review process. Would like to know any thought or feedback about the new tool.

**Comment by nickcbarone** [comment] 2022-12-08 16:38
Hi @yuzh174, thank you so much for the fix. I was able to train our data last night and it went well. My background is in product management at tech startups with over 8 years of experience and I've been using Wit since 2017. I'd love to schedule a call and give you my feedback or happy to chat via email as well. Let me know what works.

**Comment by yuzh174** [comment] 2022-12-08 19:22
Glad to hear that fixes your issue! 
That would be great if we can hear feedback from you. If that's ok with you, could you send your feedback to help@wit.ai and we will follow up. We can schedule a call from there as well.

**Closed as completed** 2022-12-12 16:58 UTC
