### ISSUE TITLE
Delete Training values and expressions permanently

### ISSUE THREAD

**Issue by ankursrivastava2** [wit-ai/wit#1075] opened 2018-05-09 07:49 UTC
I want to delete the trainings done permanently. If i delete from wit and download the app data, all the old data is also present.. How can i hard delete the training and values.

**Comment by l5t** [comment] 2018-05-09 16:08
Hello, not sure what you're trying to do... Do you want to delete your account and all the data? or just the training data of a specific app?

**Comment by l5t** [comment] 2018-05-09 16:36
I just tried the following and it worked for me.
Export an existing app
Then go in the Wit Console and delete one of the validated expressions
Export the app and I could not find the deleted expressions.

**Comment by ankursrivastava2** [comment] 2018-05-10 06:16
@l5t ... The roblem is, i need to remove a certain part of the training for a particular entity. Need to remove few values and its associated expressions for a particular entity.After removal i need to create a new app with the app data after removal.  When i remove the date from the console  and export the app, I can still find the expressions in Expression.json file . The data is not getting removed after removal from console.

**Comment by l5t** [comment] 2018-05-10 15:45
I cannot reproduce unfortunately as described above, can you share your app id and a step by step to reproduce?

**Comment by l5t** [comment] 2018-05-30 23:53
closing, please reopen if you still have the issue

**Closed by l5t** 2018-05-30 23:53 UTC
Labels: cannot-reproduce
