### ISSUE TITLE
"Connection refused" when trying to use wit API for speech recognition

### ISSUE THREAD

**Issue by farooqkz** [wit-ai/wit#1417] opened 2019-04-11 14:52 UTC
**What is the current behavior?**
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/speech_recognition/__init__.py", line 968, in recognize_wit
    response = urlopen(request, timeout=self.operation_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/farooqkz/py/soosk/pymumble_py3/mumble.py", line 119, in run
    self.loop()
  File "/home/farooqkz/py/soosk/pymumble_py3/mumble.py", line 194, in loop
    self.read_control_messages()
  File "/home/farooqkz/py/soosk/pymumble_py3/mumble.py", line 268, in read_control_messages
    self.dispatch_control_message(type, message)
  File "/home/farooqkz/py/soosk/pymumble_py3/mumble.py", line 274, in dispatch_control_message
    self.sound_received(message)
  File "/home/farooqkz/py/soosk/pymumble_py3/mumble.py", line 493, in sound_received
    self.callbacks(PYMUMBLE_CLBK_SOUNDRECEIVED, self.users[session.value], newsound)
  File "/home/farooqkz/py/soosk/pymumble_py3/callbacks.py", line 87, in __call__
    self.call_callback(callback, *pos_parameters)
  File "/home/farooqkz/py/soosk/pymumble_py3/callbacks.py", line 83, in call_callback
    func(*pos_parameters)
  File "./bot.py", line 36, in sound_received_handler
    message = recognizer.recognize_wit(audio, wit_key)
  File "/usr/local/lib/python3.6/dist-packages/speech_recognition/__init__.py", line 972, in recognize_wit
    raise RequestError("recognition connection failed: {}".format(e.reason))
speech_recognition.RequestError: recognition connection failed: [Errno 111] Connection refused
`
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I use the speech_recognition Python module.
https://notabug.org/farooqkz/soosk/src/master/bot.py#L36

**What is the expected behavior?**
Returning the text

By the way, I do it on a computer from Iran.

**Comment by farooqkz** [comment] 2019-04-12 15:56
Also sometimes I get "Network unreachable".

**Comment by farooqkz** [comment] 2019-04-13 07:28
Using pywit I get this error:
```
HTTPSConnectionPool(host='api.wit.ai', port=443): Max retries exceeded with url: /speech (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb614bc4c>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```
Or this:
```
HTTPSConnectionPool(host='api.wit.ai', port=443): Max retries exceeded with url: /speech (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb6091c6c>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by patapizza** [comment] 2019-04-15 17:07
Hi @farooqkz, can you try using curl directly? Is your network working properly?

**Comment by farooqkz** [comment] 2019-04-15 17:46
```
[22:14:39]:~$ curl -XPOST 'https://api.wit.ai/speech?v=20170307' -i -L -H "Authorization: Bearer mytoken" -H "Content-Type: audio/wav" --data-binary "@3.wav" -v --trace -
Warning: --trace overrides an earlier trace/verbose option
Note: Unnecessary use of -X or --request, POST is already inferred.
== Info:   Trying 10.10.34.35...
== Info: TCP_NODELAY set
== Info: connect to 10.10.34.35 port 443 failed: Connection refused
== Info: Failed to connect to api.wit.ai port 443: Connection refused
== Info: Closing connection 0
curl: (7) Failed to connect to api.wit.ai port 443: Connection refused
```

**Comment by aforaleka** [comment] 2019-04-15 19:43
Hey @farooqkz , "failed to connect" errors are most likely problems with your network configuration. Can you try updating your firewall settings to permit our IPv6 addresses?

**Comment by farooqkz** [comment] 2019-04-16 14:56
I don't have IPv6 networking at all.

**Comment by farooqkz** [comment] 2019-04-16 16:03
I just noticed when it is like this(refusing connections), I can't login with Github

**Comment by aforaleka** [comment] 2019-04-16 19:55
Closing since this is not specific to Wit, you'll need ipv6 networking.

**Closed by aforaleka** 2019-04-16 19:55 UTC
Labels: need-more-info, speech

**Comment by aforaleka** [comment] 2019-04-22 17:26
@farooqkz unfortunately I'm not a network expert; I suggest looking up how you can configure your specific networking to ensure stable connections to sites like Github and us.

**Comment by farooqkz** [comment] 2019-04-23 14:34
I don't have any problem with GitHub.

**Comment by jtliao** [comment] 2019-04-29 14:43
Unfortunately I don't think we can help you much further here, as we can't reproduce

**Comment by farooqkz** [comment] 2019-05-01 08:34
As I already commented I don't have this problem all the time. For periods of time in a day I can't use the API nor I can login through Github(not related to Github but to Wit.ai, the page which redirects to Github is not available then)

**Comment by patapizza** [comment] 2019-05-06 17:11
The sporadic behavior might be due to your internet connection.
