### ISSUE TITLE
Validating in Inbox 

### ISSUE THREAD

**Issue by macasas** [wit-ai/wit#379] opened 2017-02-21 21:28 UTC
Each time I validate an entry in Inbox, it disappears and then it pops back in 2 or 3 seconds later at the top of the list. 

The bot has not been released yet, no-one is adding messages while I do it, its the same massages coming back again and again.

What's going on? How can I clear these messages, using them to train and validate?

**Comment by bmcclenahan** [comment] 2017-03-07 11:46
I have been having this same problem for the last 5 days. I validate all the entries in the inbox and they come back again later or the next day. Each time the entities are identified differently - sometimes there is nothing to correct as it remembers the previous validation, other times it misses things, when the contact entity is playing up it identifies every word as a separate contact.

Is anything being done about this ? It's very reproducible.

**Comment by magnusburton** [comment] 2017-03-08 21:36
Also been seeing this lately. Saving (validating) and loading the inbox is also taking forever to process.

**Comment by l5t** [comment] 2017-03-08 22:56
can one of you share their app id so that we can investigate?

**Comment by bmcclenahan** [comment] 2017-03-08 23:21
Hi Laurent,


Thanks for following up.

I have seen the behaviour in the following 2 apps over the past week:


https://wit.ai/brucemcclenahan/mpc/inbox/semantic

https://wit.ai/brucemcclenahan/churchbot/inbox/semantic


last night, rather than clicking Validate once again on the returning items, I clicked trash and the items do not seem to have returned.


regards

Bruce


________________________________

**Comment by l5t** [comment] 2017-03-09 06:30
would be great to know if you can consistently reproduce?

**Comment by macasas** [comment] 2017-03-09 07:06
magnusburton: I don't think this is the same issue.

bmcclenahan: your issue sounds the same as mine.

l5t: Here is my link. It does this 100% of the time for me, I hope that is consistent enough for you. 
https://wit.ai/davidmacdougall/HelpMeCOOK/inbox/semantic

**Comment by l5t** [comment] 2017-03-09 07:21
haha thanks will look at it tomorrow with the team

**Comment by magnusburton** [comment] 2017-03-09 07:47
@macasas I'm also seeing what you're seeing. I can validate my entire inbox and then press reload and then all of my 'validated' messages comes back again. So I think we're seeing the same issue. Just wanted to state that validating and loading is super slow as well.

witt.ai/magnusburton/Lisa_SV

**Comment by bmcclenahan** [comment] 2017-03-09 08:51
after validating the same inbox entries over and over again, I decided to click trash icon. they haven't come back, which is good, but I now cannot reproduce the issue.

**Comment by macasas** [comment] 2017-03-09 14:43
Yes, if I delete the entry it disappears and does not come back, but of course that doesn't help train the system.

Are you saying that you can delete an entry, then when the entry appears in your inbox again, you can validate it, and it disappears from the inbox?

**Comment by bmcclenahan** [comment] 2017-03-09 23:56
@macasas My experience was like yours - after deleting the entry it did not come back again. Entries since then seem to have behaved normally.

**Comment by blandinw** [comment] 2017-03-21 18:35
Closing as duplicate of #402, will continue tracking there

**Closed by blandinw** 2017-03-21 18:35 UTC
