### ISSUE TITLE
Meassge endpoint is not working 

### ISSUE THREAD

**Issue by NourShalabi** [wit-ai/wit#1117] opened 2018-06-20 06:46 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug 
**What is the current behavior?**
This is the response being returned from the message endpoint 

{
    "data": [
        {
            "__wit__legacy_response": {
                "_text": "what is this",
                "entities": {},
                "msg_id": "0JvZ6ltIWOlb2nCb1"
            }
        }
    ]
}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Send anything to message endpoint 

**What is the expected behavior?**

**What is the App ID where you are experiencing this issue (if applicable)?**
5a5c7dac-3703-4f23-8a3e-896712f5c2f8

**Comment by blandinw** [comment] 2018-06-20 07:07
We're looking into it

**Comment by stopachka** [comment] 2018-06-20 07:14
Hey @NourShalabi, apologies for this -- human error, intern. Working on getting this into prod asap.

**Comment by blandinw** [comment] 2018-06-20 07:36
The root cause is a bad commit written by an intern + an oversight during human review.
We pushed a fix as soon as the issue was reported. Unfortunately, the FB continuous deployment system takes a few hours to propagate the new code worldwide.
The current ETA is 5 hours. We are taking this incident very seriously and sincerely apologize for the inconvenience. Proper steps will be taken to make sure this does not happen again in the future.

**Comment by NourShalabi** [comment] 2018-06-20 07:40
@blandinw , @stopachka  thank you very much guys, I know it's late now and I appreciate the quick response.

**Comment by lwallent** [comment] 2018-06-20 07:40
Thumbs up. Please be kind to the intern :-)

**Comment by alexandruf** [comment] 2018-06-20 09:08
Thank you for the update on this matter.
I have a question regarding this: are you going to modify the response in the future?
I'm asking this because that "__wit__legacy_response" object appeared from an idea. I presume :)

And also, if you are going to change the response, the v=date query parameter will preserve the old response for a previous version?

Thank you and we are looking forward for this issue to be resolved.

**Comment by blandinw** [comment] 2018-06-20 16:53
@alexandruf While we encourage users to update their version of the API, we're committed to backwards-compatibility. We won't change the format of the response. The `__wit_legacy_response` bit you're seeing refers to our legacy stack (built as a startup) vs. the non-legacy stack (relying on very robust/reliable FB technologies)

**Comment by blandinw** [comment] 2018-06-20 16:54
Fix was deployed at 4am Pacific time (Wed Jun 20)

**Closed by blandinw** 2018-06-20 16:54 UTC
Labels: bug, major-service-disruption
