### ISSUE TITLE
Built-in NLP failing on webhook API calls for wit entities

### ISSUE THREAD

**Issue by vdisawar** [wit-ai/wit#744] opened 2017-08-28 05:20 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
This is a bug

**What is the current behavior?**
Built-in NLP returns the following JSON on several patterns of text sent 
{ 
 "errors": [ 
  { 
     "code": "unknown", 
     "message": "Something went wrong. We've been notified" 
   } 
  ] 
} 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This is mainly happening on built-in wit entities. For example if you send 'hi' and are trying to get the wit/greetings entity or send in an email or trying to get the wit/email entity.

**What is the expected behavior?**
Supposed to return the JSON with entities that would be returned from GET /message endpoint

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by vdisawar** [comment] 2017-08-28 14:27
Update: this is also occurring on custom entities created in the wit console. Current workaround is that I'm directly calling the /message endpoint instead of relying on built-in nlp

**Comment by stopachka** [comment] 2017-08-28 16:54
@vdisawar Thanks for letting me know, looking into this, will update asap

**Comment by stopachka** [comment] 2017-08-28 17:55
Update: I see a subsection of messages are failing, looking deeper
@vdisawar if you could let me know more info as well, would appreciate it:
 - What is your facebook app id?
 - Do you notice this happening on specific messages?

**Comment by vdisawar** [comment] 2017-08-28 18:12
Facebook app id: 400104043685216

Honestly, it's very random. I initially noticed it mainly failing on built in entities (e.g. email and greetings) but sometimes those entities work and custom entities I've created sometimes fail.

**Comment by stopachka** [comment] 2017-08-28 23:54
Thanks for the flag @vdisawar 
The cause is identified, looking into a fix

**Comment by patapizza** [comment] 2017-08-29 01:53
This should be fixed now. Thanks for reporting!

**Closed by patapizza** 2017-08-29 01:53 UTC
Labels: bug
