### ISSUE TITLE
Not able to add entity values through wit entity page

### ISSUE THREAD

**Issue by mallik1055** [wit-ai/wit#1145] opened 2018-07-19 10:29 UTC
I want to request a BUG.

When adding keywords or adding synonyms or deleting an entity, Wit sometimes does not respond. I checked the network requests, to find this failed request

Request URL: https://api.wit.ai/sync?verbose=true
Request Method: PUT
Status Code: 500 Internal Server Error
Remote Address: 173.252.98.74:443
Referrer Policy: origin-when-cross-origin

Request Payload
[{"data":{"wisp":"5b505c9e-817c-42b9-8bb2-758d49ba97aa","value":"testing_entity_value"},"type":"added-wisp-value"}]

Response:
{
  "error" : "Something went wrong. We've been notified.",
  "code" : "wit"
}

This is happening intermittently, but once occurred is persistent for at least for a few minutes.

Also, adding keyword expressions programmatically throws the same error.

APP ID: 5b3c93e4-a6b3-45bd-af1e-e0c8ffbae98b
EntityName used to reproduce: testing

**Comment by mcanzerini** [comment] 2018-07-20 14:15
+1

**Comment by stopachka** [comment] 2018-07-20 21:50
Hey team, this could have been caused by an intermittent failure with a part of our infra. Tracking in #1142 

Fix has been pushed. let's see if we can continue to reproduce, let's update there

**Closed by stopachka** 2018-07-20 21:50 UTC
