### ISSUE TITLE
/converse return error 408

### ISSUE THREAD

**Issue by omidai** [wit-ai/wit#717] opened 2017-08-11 14:58 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**
https://api.wit.ai/converse?v=20160526 return error 408
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
return 200
**What is the App ID where you are experiencing this issue (if applicable)?**
58751046-afca-4fe5-ba1b-bac58b2ebd3f

**Comment by blandinw** [comment] 2017-08-11 17:11
@omidai are you still experiencing the issue?
How frequent was this issue?
Could you please provide precise timestamps to help investigate the cause?

**Comment by omidai** [comment] 2017-08-11 17:15
Thanks it works now , it happened around 15:45 (GMT)

**Comment by blandinw** [comment] 2017-08-11 17:34
Thanks, I'll close the issue now. Please feel free to reopen and provide precise timestamps if anything goes wrong again.

**Closed by blandinw** 2017-08-11 17:34 UTC
Labels: need-more-info
