### ISSUE TITLE
wit/contact training seems to have gone haywire

### ISSUE THREAD

**Issue by big-Bong** [wit-ai/wit#380] opened 2017-02-22 15:43 UTC
Since yesterday, the wit/contact entity in my app, which was working nearly perfectly seems to have lost all its training.
Even simple sentences like "My name is {name}" are not being caught. Retraining it is not helping. Also, wit seems to have gone into a permanent training mode and does not seem to be stabilising (it's been more than 30 hours since I saw the green dot in my wit app).

**Comment by blandinw** [comment] 2017-02-22 18:38
@big-Bong wit/contact (English) seems to be working fine on our end.
Could you provide us with more information about how to reproduce the issue?

**Comment by big-Bong** [comment] 2017-02-23 07:17
@blandinw - I'm not sure how to reproduce the issue exactly. What did happen was that wit/contact got trained on some 25-30 (+- 10) negative sentences. Before that, it was already trained on around 2000 correct sentences. When we came to know about it, we removed those sentences from the expression list.
But just that much seemed to have completely messed the previous training.
Since then, we have been training wit continuously but it has started behaving very randomly. At times it would start catching entire sentences as contact. At times it won't catch anything.
The kind of sentences on which we have been training are the sort:
{name}
My name is {name}
I am {name}
Hey there, this is {name}
{name} here
We have fed around 1500 of such sentences but to no avail. I'm not sure whether this will be of any help or not but that is all that we have been doing for the past 2 days. :)

**Comment by bmcclenahan** [comment] 2017-02-25 02:11
I have been experiencing the same issue for a number of weeks. It is intermittent and difficult to reproduce.
Quite often my users just enter someone's name. Previously it was always assigned to an entity - mostly contact sometimes location (depending on the name) and code logic took care of that. Increasingly these names are not assigned to an entity at all. I used to instruct people to enter "Who is (name)" and for the past week the API has been returning "who" as the contact.

**Comment by aravindtal** [comment] 2017-03-02 12:15
@blandinw 
I am also facing the same issue, it used to work fine before, but now it went haywire and I have this below observation. I have trained a project to extract wit/contact from the 
user utterances. Wit responds with the wit/contact properly in normal cases, but as soon
it fails for some utterance, it fails consecutively till resolve the failed one from the inbox.
This is causing a real trouble for my slack bot which is live in production. Is there a way to fix this, any help will be really helpful.

**Comment by bmcclenahan** [comment] 2017-03-06 06:14
This problem is still current and is causing major issues with my Facebook Messenger bot which is live in production.

Is anyone at Wit working on it ? 

Would it be possible to get a progress report. 

Please let me know if there's a workaround I can use or anything I can do to assist with resolving it.

**Comment by blandinw** [comment] 2017-03-06 22:08
@aravindtal are you experiencing the issue using wit/contact?

@bmcclenahan apologies for the lack of responsiveness, we'll do a better job at keeping you all posted on our progress. We've been hard at work moving Wit to the facebook.com stack to guarantee a very strong reliability. However, making sure nothing breaks is our top priority. Looking at it.

**Comment by bmcclenahan** [comment] 2017-03-06 22:39
Hey Willy,

Thanks so much for the contact, and for working on this issue.
I can’t imagine how difficult it is to resolve this stuff.

Do you have any idea of how long it will continue ?
Please keep us posted when you have time

Thanks
Bruce

**Comment by blandinw** [comment] 2017-03-08 09:02
@bmcclenahan @big-Bong I trained and deployed a new version of wit/contact. Please let me know if it behaves well. If not, please provide me some failing test sentences.

**Comment by big-Bong** [comment] 2017-03-08 11:21
@blandinw - That's great.
We have managed to create a model of our own for detecting contacts currently and have been using that for the past one week, hence wasn't able to check in during last week. Hope you fix the issue soon, since it's still not catching anything. Also, even after more than 10 days, wit still is in "training" mode.

**Comment by blandinw** [comment] 2017-03-08 11:27
The issue should now be fixed! Please feel free to reopen this ticket if needed.

**Closed by blandinw** 2017-03-08 11:27 UTC
Labels: investigating
