### ISSUE TITLE
Looping w/ bookmark breaks the app on the 12th response

### ISSUE THREAD

**Issue by tpizzle** [wit-ai/wit#531] opened 2017-04-28 01:53 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Question

**What is the current behavior?**

Looping w/ bookmark breaks story after a fixed amount of loops.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

My bot is set up to read articles in small chunks. If I want to continue to the next section, I simply say "⏭". My story is set up to move to the next section and loop back to the same branch of the story. The problem I'm running into now is, I can say "⏭" or "Next" 11 times, and on the 12th "⏭" response the story breaks. I wrote a test to see if this was random, and in fact the test breaks every single time on the 12th "⏭". By "breaking", I mean that the app goes into some sort of infinite loop of repeating the current section of the article until it hits the max steps limit. Additionally, is there a way to keep the app from going into these "infinite loops" when confidence gets low/the app falls off the story?

**What is the expected behavior?**
That I could keep looping over that branch of my story without it getting confused (confidence drops to <0.01 on the 12th try, then going into this weird loop where

**What is the App ID where you are experiencing this issue (if applicable)?**
58d2c3e6-debc-4433-899a-eee73e38a912

**Comment by Giada-Z** [comment] 2017-05-03 20:12
Same question here! Can anyone help? Thanks! It's kind of urgent.

**What is the current behavior?**
Looping w/ bookmark breaks story after a fixed amount of loops.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

My bot is set to answer questions. When context "More" is updated, it is supposed to go back to the takeQuestion action via the bookmark Answering. After that if the same contexts get updated, the conversation flow breaks.

**Sample for reproduction:**
get started -> greetingMessage, update {message}
user asks a question -> takeQuestion, update and send {noanswer}{askimg}
user asks another one -> imgFeedback, update {more} -> takeQuestion, update {noanswer}{askimg}, remove {more}, then the bot is supposed to send {noanswer}{askimg} like before, but it only sends {askimg}.

**What is the App ID where you are experiencing this issue (if applicable)?**
58f4e149-4d8f-409a-993c-56d4289cb87d

**Comment by tpizzle** [comment] 2017-05-05 05:55
@blandinw  have you guys been able to find any bugs related to this? I'm noticing that after 12 user inputs w/ any bookmark involved, my stories are breaking consistently. My app logic is getting complex enough that 12 user inputs isn't actually all that unusual, and I'm unable to really make the app widely available due to this issue. Is there anything I can do in the structure of my stories to avoid this? I'm noticing a magic number of 12 as being where my stories are breaking repeatedly.

**Comment by tpizzle** [comment] 2017-05-29 07:53
@Giada-Z did you ever find a solution?

**Comment by tpizzle** [comment] 2017-05-31 23:42
Ok it looks like this is now working better. I still get low confidence after about 10 responses or so, but the application continues to make the correct predictions. It's still very concerning that the confidence drops so low, but at least I can continue with my actions!

**Comment by l5t** [comment] 2018-01-22 01:23
Closing since we will stop Stories and serving requests to the associated /converse endpoint on February 1, 2018: https://wit.ai/blog/2017/07/27/sunsetting-stories

**Closed by l5t** 2018-01-22 01:23 UTC
Labels: stories
