### ISSUE TITLE
Wit number is not working

### ISSUE THREAD

**Issue by 51100807** [wit-ai/wit#1786] opened 2020-06-01 06:41 UTC
1.  It is a bug.
2.  Current behavior:
The wit/number wrong recognition entities.
a. 2 người lớn (mean 2 adult)
wit/number:price: 2
b. 3 người lớn(mean 3 adult)
wit/number:price: 3
c. 2 trẻ em (mean 2 childs)
wit/number:price: 2
d. 4 tuổi (mean 4 age)
wit/number:price: 4
e.2 gia đình (mean 2 family)
wit/number:price: 2
3.  Expected behavior like before (yesterday)
a. 2 người lớn
wit/number :adult : 2
b. 3 người lớn
wit/number: adult : 3
c. 2 trẻ em
wit/number: child : 2
d. 4 tuổi
wit/number :childsage : 4
e.2 gia đình
wit/number: family : 2
4. AppID: 1778316165603240
![Screenshot_1](https://user-images.githubusercontent.com/11769396/83382499-6a1c6f80-a40d-11ea-8891-d49a8c0e1724.png)
![Screenshot_2](https://user-images.githubusercontent.com/11769396/83382504-6b4d9c80-a40d-11ea-899b-0bbc777d0e74.png)
![Screenshot_3](https://user-images.githubusercontent.com/11769396/83382538-7d2f3f80-a40d-11ea-8a37-882c0f92ec9c.png)
![Screenshot_4](https://user-images.githubusercontent.com/11769396/83382540-7e606c80-a40d-11ea-8d08-4abb84b646fb.png)

Please help to check.

**Comment by jtliao** [comment] 2020-06-01 23:19
This should be fixed for your app now. The overall fix is still in progress, I'd recommend not re-training your app until I report back that the issue is fully fixed (should be a few hours).

**Comment by jtliao** [comment] 2020-06-02 04:45
The problem should be fixed now.

**Closed as completed by jtliao** 2020-06-02 04:45 UTC
Labels: bug

**Comment by 51100807** [comment] 2020-06-02 06:38
ok thank @jtliao , it works

**Comment by homelander03** [comment] 2020-06-04 05:52
APP IDs: 2741036935962163, 2529044864091611.
properties below 20 lakhs - 20 lakhs is getting detected as wit:number:lk.
properties above 20 lakhs - 20 lakhs is not getting detected at all.
It is happening with all my apps, It should detect number with role for both.

**Comment by patapizza** [comment] 2020-06-04 21:03
@mohansr03 It's because some of your utterances are validated with `wit/number` and `priceUnit` separately, as opposed to `wit/number` fully:

<img width="484" alt="Screen Shot 2020-06-04 at 2 00 10 PM" src="https://user-images.githubusercontent.com/1015208/83809823-f62bd280-a66b-11ea-9368-8d02f33a8a8f.png">

Might be worth adding `lakhs` support to [Duckling](https://github.com/facebook/duckling) so you can use `wit/amount_of_money` directly for that.
