### ISSUE TITLE
Keyword matches, despite an extra character at end. ex: `lad` matches keyword `la`

### ISSUE THREAD

**Issue by yegeniy** [wit-ai/wit#832] opened 2017-10-24 17:05 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

bug

**What is the current behavior?**
keyword entities match words that have an extra character at the end of word

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
{
  "msg_id": "localtesting.1508864236",
  "_text": "lad",
  "entities": {
    "organization": [
      {
        "confidence": 1,
        "value": "Los Angeles",
        "type": "value",
        "_entity": "organization",
        "_body": "la",
        "_start": 0,
        "_end": 2
      }
    ]
  }
}

{
  "msg_id": "localtesting.1508864243",
  "_text": "lads",
  "entities": {}
}

{
  "msg_id": "localtesting.1508864551",
  "_text": "la works, though",
  "entities": {
    "organization": [
      {
        "confidence": 1,
        "value": "Los Angeles",
        "type": "value",
        "_entity": "organization",
        "_body": "la",
        "_start": 0,
        "_end": 2
      }
    ]
  }
}

{
  "msg_id": "localtesting.1508864264",
  "_text": "lax",
  "entities": {
    "organization": [
      {
        "confidence": 1,
        "value": "Los Angeles",
        "type": "value",
        "_entity": "organization",
        "_body": "la",
        "_start": 0,
        "_end": 2
      }
    ]
  }
}

{
  "msg_id": "localtesting.1508864422",
  "_text": "lad, you are off by huan",
  "entities": {
    "organization": [
      {
        "confidence": 1,
        "value": "Los Angeles",
        "type": "value",
        "_entity": "organization",
        "_body": "la",
        "_start": 0,
        "_end": 2
      }
    ]
  }
}
```

**What is the expected behavior?**

Only the keyword which was trained should match. In the example above, only `la` should have matched `Los Angeles` 

**What is the App ID where you are experiencing this issue (if applicable)?**

59ef3f06-c2ba-429b-babb-ec687f8cf01c (and some other ones)

**Comment by stopachka** [comment] 2017-10-25 21:14
Thanks for reporting @yegeniy -- looks like it's highlighting [la] from [la]d -- most likely us trying to be helpful with levenstein distances. Will let you know as I research deeper

**Comment by yegeniy** [comment] 2017-10-26 20:14
Thanks @stopachka - that'd be an interesting use case, actually: using wit.ai to optionally run some common algorithms. 

For example, we have a use case where it might be useful to pass the utterance through some [phonetic algorithm](https://en.wikipedia.org/wiki/Phonetic_algorithm) to help detect entities despite periodically poor speech-to-text transcription. I suspect we're not the only users that are using STT and passing it through wit.ai.

**Comment by yegeniy** [comment] 2018-01-02 22:28
Hey @stopachka. This still seems to be a bug. The utterance `all-star` is being detected as the entities `al` and `star`.

**Comment by stopachka** [comment] 2018-01-18 18:45
Yes indeed @yegeniy! 

Diff for a fix is coming soon. 

for the utterance `all-star`, would you have wanted the keyword `star` to have been detected?

**Comment by yegeniy** [comment] 2018-01-19 19:07
Hi @stopachka, 

Thank you! 

-------

> for the utterance `all-star`, would you have wanted the keyword `star` to have been detected?

No, just `all-star` in that case.

This hints at another common issue  we have with wit.ai We have noticed that the shortest entities seem to be preferred instead of the longest. This might be a regression from a while ago, because I think it used to prefer picking up the longest entities. Might be easier to explain with an example.

We have the substrings `all star` and `all-star` as synonyms of an entity (i.e. baseball's All-Star Game) and would like to have them be detected. Note that, even though we also have the keyword `star` as a synonym of the entity `Astros` (i.e. the baseball team), we wouldn't want it detected in the presence of the substrings "all-star" or "all star". For example:

> Which all star team won?

Only the entity for `all star` should be detected. At least, that's the case that makes sense to us...

> Which Star got the most home runs this season

The entity for `star` should be detected here.

P.S.: I think there's a separate GitHub issue someone else opened as well about this. I think I commented on it.

**Comment by stopachka** [comment] 2018-01-25 21:30
Hey @yegeniy 

Ship landed for the la[d] fix. 

The root cause is: 
- When we detect a word, that is off only by one character -- i.e 
 - "bagelz", or "yess"
   - we would forgive just the next character.
      - but for such a small keyword, like "la". this does not make sense. 

re: shorter vs longer entities
- we are looking into this now, and will update on that task with thoughts or questions

**Closed by stopachka** 2018-01-25 21:30 UTC
Labels: bug

**Comment by yegeniy** [comment] 2018-01-26 04:01
> When we detect a word, that is off only by one character -- i.e"bagelz",
or "yess"we would forgive just the next character.

Ah! Nice. That explains that magic :)

And thank you for considering longer vs. shorter entities! Please let me
know if there's anything else we can do to help (examples, etc... I believe
you have our contact info, the emails with the domains @mlb.com).
