### ISSUE TITLE
Training the model using PUT https://api.wit.ai/entities/$ENTITY_ID updates the wit.ai UI but doesn't seem to update the model

### ISSUE THREAD

**Issue by josephlingzb** [wit-ai/wit#1008] opened 2018-03-20 01:15 UTC
Hi, Im using PUT https://api.wit.ai/entities/$ENTITY_ID to update the expressions. The new expressions can be seen on the wit.ai console, but inputting the exact expression never goes to the correct intent.

For e.g., on app-id 5a336efc-05fb-4775-b180-5e8c2be881cf, I added an intent called Test Intent with one expression: "test intent" using the PUT api. The update shows up on wit.ai UI but when I input "test intent" it never gets the correct intent.

**Comment by patapizza** [comment] 2018-03-20 16:07
Thanks @josephlingzb. This might be a duplicate of #1010.

**Comment by josephlingzb** [comment] 2018-03-21 02:14
Hi @patapizza, hmm I don't think it the same issue. #1010 seems to be just a delay on training. Check out this app-id 5aaf874d-49c1-429a-ab63-094334dcc2dc. I have an intent called "Hi" with the expression "hi" trained. This was done almost 12 hours ago, yet testing the expression "hi" does not give any intent at all.

**Comment by l5t** [comment] 2018-03-21 15:47
12 hours seems a lot, we may have had an issue with our training loop. Do you mind testing adding a new entity with PUT and wait for a few minutes

**Comment by nirmaljosep** [comment] 2018-03-28 13:18
same issue here appid:5aba14c0-f06e-4346-8fcb-4bff155823da

**Comment by l5t** [comment] 2018-03-28 15:09
https://github.com/wit-ai/wit/issues/1021#issuecomment-376880686

**Closed by l5t** 2018-03-28 15:09 UTC
