### ISSUE TITLE
App training changes

### ISSUE THREAD

**Issue by 91ns** [wit-ai/wit#1143] opened 2018-07-17 08:30 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
I trained one of my apps yesterday from a list of entities, today I found the app like this 
![image](https://user-images.githubusercontent.com/25252530/42805474-928f0d6c-89b4-11e8-8680-e71f373b9de0.png)

I did not add 509 entities. How did this happen?

**What is the App ID where you are experiencing this issue (if applicable)?**
5b4c9400-1084-4cb7-ba75-64a8337cfe7b

**Comment by stopachka** [comment] 2018-07-22 20:52
Hey Nour, this could have been caused by:
- sending POST /samples requests
- and deleting one of the entities in the meantime

Do you think something like this could have happened? 

If yes, it is related to this bug: https://github.com/wit-ai/wit/issues/1146
(fix coming soon)

**Comment by 91ns** [comment] 2018-07-24 07:34
hmmm... it is possible, but does that cause this bug to happen later on? 
Because in my case, I finished working on it, the training status was clean. Hours later I found the entities looking as in the screenshot.

**Comment by stopachka** [comment] 2018-07-24 17:32
Hey Nour -- here's how it could have happened

t0: Send POST /samples with entity a, values: b, c
- *the samples queue is backed up, maybe from a different user*
t1: delete entity
t2: samples queue finally reaches your sample, boom bug

A fix should be coming soon for this bug, indeed it's quite surprising that this can happen.

**Comment by jtliao** [comment] 2018-09-19 15:07
this is now fixed, POST /samples won't create entities anymore

**Closed by jtliao** 2018-09-19 15:07 UTC
