### ISSUE TITLE
POST /samples fails with generic error or succeeds but doesn't update expressions

### ISSUE THREAD

**Issue by jaisrael1** [wit-ai/wit#1263] opened 2018-11-07 22:37 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Report a bug

**What is the current behavior?**

Recently when I send training data using the POST /samples endpoint, it has often failed with the error message : { "error" : "Something went wrong. We've been notified.", "code" : "wit" }. If I send the samples again a minute later, it appears to succeed and I get back the message { "sent" : true, "n" : 200 }. However, none of the samples are actually trained. When I look at the app in the wit console it remains unchanged and sending any of the new training data to GET /message comes up with no results. 

In addition, the training status never changes to reflect this batch of training, either in the console or through GET /apps/:app-id.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Push a large amount of training samples (My case is about 1100 in sequential batches of 200) through the POST /samples endpoint and see if it works

UPDATE: This is also happening in my older apps, which are much smaller. There is no error and I get back a confirmation message { "sent" : true, "n" : 81 }. Despite this, the training status never changes and the samples are never trained.

**What is the expected behavior?**

The samples should be trained if I am getting a confirmation response

**What is the App ID where you are experiencing this issue (if applicable)?**

Bigger app: 2135298379834784
Old smaller app: 5b61f3c2-3542-49f5-a8dc-485db08b3ebc

**Comment by jtliao** [comment] 2018-11-10 02:20
hey @jaisrael1, sorry for the delay-- are you still experiencing the issue? We were having an issue with our queue being blocked up, so we were processing samples very slowly.

**Comment by jtliao** [comment] 2018-11-15 01:41
The root cause of this should be fixed now.

**Closed by jtliao** 2018-11-15 01:41 UTC
