### ISSUE TITLE
Trouble loading wit.ai -- possible cors issue

### ISSUE THREAD

**Issue by nitingautam** [wit-ai/wit#1234] opened 2018-10-04 17:24 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG
**What is the current behavior?**
When you open the site it is all broken as static content not loading with ERROR CORS policy
(index):1 Access to CSS stylesheet at 'https://static.xx.fbcdn.net/rsrc.php/v3/yE/l/0,cross/WqGCWfQEHOq.css' from origin 'https://wit.ai' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://wit.ai' is therefore not allowed access.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just open the site in chrome or other browser and check console.
**What is the expected behavior?**
Web site should open and allow to login

**What is the App ID where you are experiencing this issue (if applicable)?**

**Comment by stopachka** [comment] 2018-10-04 17:29
Hi @nitingautam -- I am aiming to reproduce this, but do not see the error on our end. Will update here with more info

**Comment by nitingautam** [comment] 2018-10-04 17:33
Version 69.0.3497.92 (Official Build) (32-bit)

**Comment by nitingautam** [comment] 2018-10-04 17:34
happening in Version 69.0.3497.100 (Official Build) (32-bit) as well Chrome

**Comment by stopachka** [comment] 2018-10-04 17:42
Thanks @nitingautam -- I'm looking more deeply and will update with what we find

**Comment by stopachka** [comment] 2018-10-04 18:09
Hey @nitingautam, could you:

1. Open up "Inspector" in chrome (right click, inspector)
2. Go to "Network"
3. Filter css
4. Right click, and hit "Save HAR" 

![image](https://user-images.githubusercontent.com/984574/46493704-eb010f00-c7c5-11e8-8e46-74f38c36c221.png)

You can send that to me at stopachka [a.t] fb.com

We are currently unable to repro this, and are not seeing the error in the logs, The HAR file will let us know more clearly where the issue is coming from

**Comment by nitingautam** [comment] 2018-10-04 21:10
Please find attached, I doubt if this could be my office VPN. Let me try with other machine later today.
[wit.ai.zip](https://github.com/wit-ai/wit/files/2448143/wit.ai.zip)

**Comment by stopachka** [comment] 2018-10-18 07:45
(closing, reopen if still facing issues)

**Closed by stopachka** 2018-10-18 07:45 UTC
