### ISSUE TITLE
"error" : "Something went wrong. We've been notified.",   "code" : "wit"

### ISSUE THREAD

**Issue by terekete** [wit-ai/wit#975] opened 2018-02-19 16:42 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Not sure if this is a bug or I am missing an attr in the rest call.

**What is the current behavior?**
Using the HTTP API /samples endpoint and the default example: 

curl -XPOST 'https://api.wit.ai/samples?v=20170307' \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '[{
        "text": "I want to fly to sfo",
        "entities": [
          {
            "entity": "intent",
            "value": "flight_request"
          },
          {
            "entity": "wit$location",
            "start": 17,
            "end": 20,
            "value": "sfo"
          }
        ]
      }]'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Can run the example above.

**What is the expected behavior?**
Expected behaviour: the intent is Posted to wit api.

**What is the App ID where you are experiencing this issue (if applicable)?**

5a866301-0024-402f-8574-f5e194b9f9c1

**Comment by blandinw** [comment] 2018-02-19 17:23
@terekete I'm looking into it

**Comment by blandinw** [comment] 2018-02-19 21:11
@terekete I cannot reproduce your issue, I'll assume it is now fixed.
Thank you for your feedback!

**Closed by blandinw** 2018-02-19 21:11 UTC
