### ISSUE TITLE
Address being identified as phone number 

### ISSUE THREAD

**Issue by michaelulin** [wit-ai/wit#829] opened 2017-10-19 23:18 UTC
Do you want to request a feature, report a bug, or ask a question about wit?
bug
What is the current behavior?
The address 989 45th street oakland ca is being classified as a phone number, not a location. I've manually highlighted this and classified it as an expression in the Wit.AI platform, but it is still being classified as a phone number.

**The UI says that this is classified as a location, but the actual output still says phone (see screenshot below)**

Here is the output from the API:
[
{
"confidence": null,
"intent": "default_intent",
"_text": "989 45th st oakland ca",
"entities": {
"phone_number": [
{
"confidence": 0.9577825,
"value": "989 45"
}
]
}
}
]

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

What is the expected behavior?
Should be classified as a location.
What is the App ID where you are experiencing this issue (if applicable)?
59dbb6a6-5341-4dfe-88c7-a5c1b47a730c

![image](https://user-images.githubusercontent.com/4452086/31798525-15d0cd24-b4e9-11e7-8fc5-b2ebaba32a92.png)

![image](https://user-images.githubusercontent.com/4452086/31798519-079d7720-b4e9-11e7-836c-f711a1685597.png)

**Comment by patapizza** [comment] 2017-10-20 14:34
Duplicate of #828. Please reopen the issue to keep context.

Can you try copy/pasting "989 45th st oakland ca" in the input instead of typing it? Might be an UX issue where we run the NLP on a shorter text first.

**Closed by patapizza** 2017-10-20 14:34 UTC
