### ISSUE TITLE
Deleting an entity produces a bunch of "stray" new entities

### ISSUE THREAD

**Issue by RobertsG** [wit-ai/wit#1146] opened 2018-07-19 10:37 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
Trying to delete an entity using the API DELETE request, but getting the following message:
```
Server error: `DELETE https://api.wit.ai/entities/small-talk?version=20180626` resulted in a `500 Internal Server Error` response:
{
  "error": "Something went wrong. We've been notified.",
  "code" : "wit"
}
```

On other apps, the delete resulted in small-talk disappearing but leaving a bunch of entities (the values of the small-talk entity) with the same ID behind.

https://www.dropbox.com/s/3dalsad2agaph3k/Screenshot%202018-07-19%2013.32.03.png?dl=0

Also, the app keeps scheduling new trainings after finishing previous one all the time.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Currently, have an entity called 'small-talk' which has over a 100 values in it, things like "How are you?" "Who are you?" and so on.
I wanted to reinsert new values with different "values" to be returned to the "texts", so I went and tried to delete the whole entity assuming it would also delete all the values in it with it. Got an error, from UI, tried to do it from the API and got the same error.

**What is the expected behavior?**
The entity gets deleted with all the values.

**What is the App ID where you are experiencing this issue (if applicable)?**
5b3256c2-98a8-45d9-b5dd-83fb4e8c6d8c
 and several others in the same profile.

**Comment by stopachka** [comment] 2018-07-20 21:52
Hey Robert, for writes failing intermittently, this may have been caused by an unexpected load onto a piece of our infra. Tracking here #1142

**Comment by stopachka** [comment] 2018-07-20 21:53
For the "ids" being created -- this could have been caused by the following race condition
- If you submitted POST /samples, these samples are put into a queue
- If while the queue has not been finished, you delete the entity, it may cause an inconsistent state, and start creating those entities
  - This is is a bug, and I will aim to push a fix. Could you confirm that you had pushed POST /samples requests while deleting?

**Comment by stopachka** [comment] 2018-07-22 16:56
Cheers @RobertsG! I'll bring this up as a bugfix, to prevent samples from creating non-existing parsers

**Comment by jtliao** [comment] 2018-09-19 15:06
this is now fixed, thanks to @stopachka :)

**Closed by jtliao** 2018-09-19 15:06 UTC
