### ISSUE TITLE
Emojis return 500 from wit

### ISSUE THREAD

**Issue by exs6350** [wit-ai/wit#754] opened 2017-08-30 21:13 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
When a user types in an emoji (in ASCII) I get back a 500 from wit. Currently using the python wit library. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1.) user types in ":)"
2) My server makes a request to wit with user message 
3) I get back a 500 response from wit

**What is the expected behavior?**
Wit to return an a json object with no matched entities

**What is the App ID where you are experiencing this issue (if applicable)?**
598ddb6f-f8f9-4a3e-940f-682ed0eb9bae

**Comment by patapizza** [comment] 2017-08-30 21:50
Thanks for reporting @exs6350. I'll look into it.

**Comment by patapizza** [comment] 2017-08-31 22:27
Root cause found, fixing.

**Comment by patapizza** [comment] 2017-09-01 01:52
This is now fixed.

**Closed by patapizza** 2017-09-01 01:52 UTC
Labels: bug, investigating
