### ISSUE TITLE
Bug : cannot learn a word with trait strategy

### ISSUE THREAD

**Issue by LokoSama** [wit-ai/wit#1127] opened 2018-07-03 08:40 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
The behaviour is one word not being learned by the model. I have one intent strategy using traits to recognize different types of text. When I validate the word "salut" as "greetings" value, the model never learns and "salut" remains not matched. The other words are learned correctly.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Steps to reproduce :
1) Validate "salut" as entity "intent" with value "greetings"
2) Wait for the model to learn
3) Try "salut" understanding : not recognized

**What is the expected behavior?**
The word "salut" should be recognized as "intent" entity with "greetings" value

**What is the App ID where you are experiencing this issue (if applicable)?**
59d5db09-8c74-4352-b3e7-aff7601d32dc

**Comment by patapizza** [comment] 2018-07-05 23:49
Hi @LokoSama,

You had 2 samples validated without the "intent" entity: `Salut` and `salut `. I validated with the intent "greetings", and the problem is now fixed.
We're working on surfacing those badly annotated examples.

**Closed by patapizza** 2018-07-05 23:49 UTC
