### ISSUE TITLE
Nodes sdk for wit ai messenger js file invalid json response

### ISSUE THREAD

**Issue by hoerlanton** [wit-ai/wit#698] opened 2017-08-06 16:19 UTC
I wanted to get started with the Node.js SDK for Wit.ai. I followed the steps according to the comments in the messenger.js file:

// 1. npm install body-parser express request

// 2. Download and install ngrok from https://ngrok.com/download

// 3. ./ngrok http 8445

// 4. WIT_TOKEN=your_access_token FB_APP_SECRET=your_app_secret FB_PAGE_TOKEN=your_page_token node examples/messenger.js

// 5. Subscribe your page to the Webhooks using verify_token and https://<your_ngrok_io>/webhook as callback URL.

// 6. Talk to your bot on Messenger!

When I send a message to the server via Facebook messenger I receive the following error:

invalid json response body at https://f91805fe.ngrok.io/converse?session_id=2017-08-06T15%3A37%3A04.862Z&q=ldldl reason: Unexpected token T in JSON at position 0 invalid-son Oops! Got an error from Wit: Error at /Users/antonhorl/Documents/projekte-lokal/HotelMessenger/bots/node-wit-bot/node_modules/node-fetch/lib/body.js:49:31 at at process._tickCallback (internal/process/next_tick.js:188:7)

Has somebody any idea why? Thanks a lot for the effort.

**Comment by patapizza** [comment] 2017-08-07 22:01
Node.js SDK ticket: https://github.com/wit-ai/node-wit/issues/153

**Comment by iamkenken** [comment] 2017-08-10 09:21
got the same problem.

**Comment by blandinw** [comment] 2017-08-14 23:40
Not sure this is specific to Node.js SDK.
@iamkenken @hoerlanton can you provide your app ids and steps to reproduce the issue?

**Comment by iamkenken** [comment] 2017-08-15 06:11
@blandinw The response from wit is working right now but there are times that the response is not working and it happens everyday. I'm just not sure what time. Is it because that I'm using the stories? Here is the sample response when it's not working.

Error: FetchError: invalid json response body at https://api.wit.ai/converse?session_id=8cae3fc1517e2f1ba275de42&q=Tondo reason: Unexpected token S in JSON at position 0

**Comment by blandinw** [comment] 2017-08-15 18:41
Thanks @iamkenken, this helps, I'll investigate internally.
Precise timestamps would help if you can provide them.

To your question, it is due to the fact that you're using Stories. It should still work so we'll try to fix that, but we highly recommend you move over to using Understanding + GET /message API (more context @ https://wit.ai/blog/2017/07/27/sunsetting-stories)

**Comment by fmartinez-oneloop** [comment] 2017-08-22 13:48
@blandinw Hi, we are also using stories and we were told that support for them will be mantained until the end of the year. Nevertheless, we are having the same issue mentioned above:

```
SyntaxError: Unexpected token S in JSON at position 0
     at Object.parse (native)
     at /var/lib/strong-pm/svc/1/work/c5de636719749fc481da6db4c69c2aba1b90f46d.1490025319357/node_modules/node-wit/node_modules/isomorphic-fetch/node_modules/node-fetch/lib/body.js:49:15
     at process._tickCallback (internal/process/next_tick.js:103:7)
```

We debug the response on that line and found that wit.ai is responding this:

`Something went wrong. We've been notified.`

We need to know if this issue is going to be solved and when, since our production app is not working and is affecting lots of our users (+5000). 

Regards,
Federico Martinez

**Comment by stopachka** [comment] 2017-08-22 16:04
Hey @fmartinez-oneloop -- we will most definitely continue to support. 

Would you mind sending me an example request, with the app-id of your service?

**Comment by stopachka** [comment] 2017-08-22 16:05
the invalid-json here is a red-herring -- will fix that as well, but the actual issue is that the backend seems to be returning a 500

**Comment by fmartinez-oneloop** [comment] 2017-08-22 17:30
Hi @stopachka. Here is the request URL we are sending to the wit.ai api that we got by configuring the client with a logger in DEBUG mode:

`POST https://api.wit.ai/converse?session_id=f0535c27-2c94-47de-93a7-460f2d29f847&q=hola`

And our app-id is:

`58418b49-ad02-45ae-a899-e966ff918854`

**Comment by patapizza** [comment] 2017-08-23 17:21
Hi @fmartinez-oneloop,

I've just tried with that session and it seems like it works:

```
$ curl -XPOST 'https://api.wit.ai/converse?session_id=f0535c27-2c94-47de-93a7-460f2d29f847&q=hola'
{
  "confidence" : 1,
  "type" : "msg",
  "msg" : "Hola, como puedo ayudarte?",
  "entities" : {
    "saludo" : [ {
      "confidence" : 0.99388070251418,
      "value" : "hola",
      "type" : "value"
    } ]
  }
```

Are you experiencing the issue consistently on your end?

**Comment by mani541** [comment] 2017-08-24 07:56
Hi,

I am  facing the same issue as well. 

App Id: 58e1c245-4e57-4a25-a87f-19b75c288742
 
Please get wit.ai up and running like how it used to be untill the timeline mentioned.

**Comment by fmartinez-oneloop** [comment] 2017-08-24 15:49
@patapizza @stopachka Apparently it is working fine today. We checked our application logs and found that yesterday at around 4:15pm (PDT) the issue stopped and wit.ai endpoint started to respond correctly. 

Have the wit.ai team made any fix on their backend to address the issue? A confirmation on this would be helpful since we want to be sure this issue won't happen again in the days to come.

**Comment by l5t** [comment] 2017-08-24 17:08
I can confirm we did fix something on our backend yesterday around that time. Closing. Feel free to reopen

**Closed by l5t** 2017-08-24 17:08 UTC
Labels: bug

**Comment by hoerlanton** [comment] 2017-08-28 20:08
Still having this issue: 

**App Id:** 58261d9c-7e06-49d3-a204-af017d6d6f9f

**Terminal output of steps:** 

[wit] Stories and POST /converse have been deprecated. This will break in February 2018!
Listening on :8445...
TEXT:test
200 POST /webhook
404 POST /converse?session_id=2017-08-28T20%3A07%3A42.778Z&q=test
Oops! Got an error from Wit:  Error
    at /Users/antonhorl/Documents/projekte-lokal/HotelMessenger/bots/node-wit/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Thanks a lot for the help!

**Comment by hoerlanton** [comment] 2017-08-28 20:55
console log in body.js lin 48: invalid json response body at https://9bde1abe.ngrok.io/converse?session_id=2017-08-28T20%3A54%3A31.509Z&q=%C3%A4 reason: Unexpected token < in JSON at position 0 invalid-json
