### ISSUE TITLE
GET converse call not working

### ISSUE THREAD

**Issue by elviraC** [wit-ai/wit#415] opened 2017-03-15 11:24 UTC
Hello,

I'm trying to get the response of the chatbot. 

I have the following POSTurl in POSTMAN:
https://api.wit.ai/converse?v=20170315&session_id=121&access_token=MyAccessToken&q=Hallo&type=stop

```
Which sends me the correct response back:
{
  "confidence": 0.031896348322735024,
  "type": "msg",
  "msg": "Hallo! Wat kan ik voor je doen?",
  "entities": {
    "begroeting": [
      {
        "confidence": 0.9077780818718217,
        "type": "value",
        "value": "Hallo"
      }
    ]
  }
}
```

When i'm trying to do a ajax call like this:
```
$.ajax({
	url: "https://api.wit.ai/converse",
	data:{
	'v': '20170315',
	'session_id':'1231',
        'q': 'Hallo',
	'type':'stop',
	'access_token':'MyAccessToken'},
	dataType:"jsonp",
	method:"POST",
	success:function(response){
		console.log(JSON.stringify(response));
	}
});

```
I'm getting the following error:
![error](https://cloud.githubusercontent.com/assets/6792395/23946319/3e1cb312-097a-11e7-8c24-0b181452a141.png)

Why does my postman call work..but ajax call doesn't?

Thanks very much!

**Comment by swapkh91** [comment] 2017-03-17 11:10
Are you running it on a server? Because it wont work without that, CORS error. I tried running it on python and it works fine. The below code is generated from postman.

`import http.client`

`conn = http.client.HTTPSConnection("api.wit.ai")`

`headers = {`
    `'authorization': "Bearer Z4QWQNVAO3B2TIY66AH7U3TUCIBECXYQ"`
    `}`

`conn.request("POST", "/converse?v=20170315&session_id=121&access_token=Z4QWQNVAO3B2TIY66AH7U3TUCIBECXYQ&q=Hallo&type=stop", headers=headers)`

`res = conn.getresponse()`
`data = res.read()`

`print(data.decode("utf-8"))`

**Comment by aeditus** [comment] 2017-07-12 09:34
Any update from this issue?

**Comment by blandinw** [comment] 2017-07-12 20:59
JSONP is for GET requests only.
Closing as duplicate of #242.

**Closed by blandinw** 2017-07-12 20:59 UTC
Labels: stories
