### ISSUE TITLE
samples have role "double negation", and entity is "double_negation"

### ISSUE THREAD

**Issue by ross-development** [wit-ai/wit#1144] opened 2018-07-17 17:23 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
When I tried to download the training data for my app, it returns the error message like the following:
`{
"error": "Something went wrong. We've been notified.",
"code": "wit"
}`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Click the button in `Export your data`

**What is the expected behavior?**
Download a compressed file with my training data

**What is the App ID where you are experiencing this issue (if applicable)?**
5b33927b-dafc-4cc0-8749-766f0c96a22d

**Comment by stopachka** [comment] 2018-07-20 21:43
Hey Ross, I took a look -- it seems there's a bug on our hands. There were some entities that had a role called "double negation", when the real role is called "double_negation" 

Fixed this for your app -- we will aim to address the root cause and close this task then

**Comment by ross-development** [comment] 2018-07-23 17:52
Thank you for the help!!

**Comment by ross-development** [comment] 2018-07-23 17:52
The problem is solved.

**Comment by ross-development** [comment] 2018-07-23 17:55
Thank you for the help!! We are able to download our training data. Sorry we accidentally closed the issue.

**Closed** 2020-01-16 15:47 UTC
