### ISSUE TITLE
Cannot train wit.ai, the Preview API Output doesn't work as expectation

### ISSUE THREAD

**Issue by vnheros** [wit-ai/wit#827] opened 2017-10-19 02:33 UTC
I'm training wit.ai for some Vietnamese entities.
In Vietnamese *đêm* = *night* in English
I already trained wit.ai with sentences:
*1 đêm*
*2 đêm*
*3 đêm*
*4 đêm*
*5 đêm*
*6 đêm*
*7 đêm*
*8 đêm*
*9 đêm*
*10 đêm*
and set role as ***wit/duration:nights***. The **Validate** button is green.
![image](https://user-images.githubusercontent.com/16472704/31751408-66679d2e-b4af-11e7-8ff6-6fd296fbbf72.png)

I expect that when I click **Preview API Output**, it will detect the entity ***wit/duration:nights***. But it cannot:
![image](https://user-images.githubusercontent.com/16472704/31751493-cea4c5b0-b4af-11e7-8392-324009384f45.png)

I think it may be a bug. Wit.ai should detect this entity any way because I trained many times.

**Comment by l5t** [comment] 2017-10-19 04:39
Thanks for reporting. This is not a bug. Wit mainly relies on Machine Learning (so based on the expressions you validated) and a little bit on a linguistic parser (that is language specific) for entities like wit/datetime or wit/duration. To help train this, you would have to look at the open source parser here: https://github.com/facebookincubator/duckling.
As you can see, we don't have yet duration so feel free to send us a Pull Request: https://github.com/facebookincubator/duckling/tree/master/Duckling/Duration 

Was your app language set to English or Vietnamese? Because if in Vietnamese, you shouldn't have had the ability to use wit/duration.

Finally role cannot be used for that. More info here: https://wit.ai/docs/recipes#differentiate-several-entities-according-to-their-role-in-the-message

**Comment by vnheros** [comment] 2017-10-19 10:39
Thanks @l5t !
My app is set to Vietnamese.
Well noted for requesting new Duration for Vietnamese.
I just want to reconfirm that we cannot set role for unavailable built-in entity (e.g. wit/duration), right?

**Comment by l5t** [comment] 2017-10-19 16:20
Ok so we have a bug here, as you should not have seen the entity Duration if not yet available on Duckling (let alone setting role). We will publish a fix for that one.

**Comment by patapizza** [comment] 2017-10-19 16:35
We actually do support `Duration` in VI: https://github.com/facebookincubator/duckling/blob/master/Duckling/Dimensions/VI.hs#L17.

The common rules provide basic support for all languages: https://github.com/facebookincubator/duckling/blob/master/Duckling/Duration/Rules.hs

Feel free to extend the `Duration` support for `VI`.

**Comment by l5t** [comment] 2017-10-19 17:55
closing then

**Closed by l5t** 2017-10-19 17:55 UTC
