### ISSUE TITLE
Not training, weird error

### ISSUE THREAD

**Issue by denzils** [wit-ai/wit#712] opened 2017-08-10 15:46 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a *bug*
**What is the current behavior?**
I'm trying to train wit and am getting the same item showing up over and over again. Also, this weird error pops up "Value does not match schema: {:semantic {:entities [{:value missing-required-key} nil]}}". This is not in my code but on the wit website.

Also is it possible to train wit programmatically instead of from the UI?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
in the Understanding tab on wit's website, I press validate and the item card shows up again after ten seconds (the validation not sticking) and eventually a yellow warning popup shows up in the right hand corner stating "Value does not match schema: {:semantic {:entities [{:value missing-required-key} nil]}}"

**What is the expected behavior?**
The expected behavior is that it validates the card and then lets me validate more cards.

**What is the App ID where you are experiencing this issue (if applicable)?**

5944985f-5dde-4c6a-8c9c-69210eda7202

**Comment by hweiler** [comment] 2017-08-10 20:49
I've been having the same issue since yesterday afternoon. None of my validated nor deleted cards in the Inbox are saving. They just reappear since the changes aren't saving.

I've also tested this on the Understanding tab, in which case I just get the validation error message.

**Comment by blandinw** [comment] 2017-08-10 22:42
@denzils @hweiler thank you for your feedback!
@hweiler could you provide me with your app-id?

**Comment by blandinw** [comment] 2017-08-10 22:44
@denzils You can train Wit programmatically using the POST /samples API. More info on using Wit programmatically: https://github.com/wit-ai/wit-api-only-tutorial

**Comment by exs6350** [comment] 2017-08-11 01:16
I also encountered this issue today, yesterday it was validating just fine. Here's how I get it: I go to my inbox to see expressions that I want to validate. I validate an expression the card disappears then reappears a couple seconds later as if nothing happened. I don't get notified that anything went wrong on the UI but I checked the console and I'm getting back a 500 error. My app id is 5953d80f-3965-4f66-997a-30d2f125f8e5

**Comment by blandinw** [comment] 2017-08-11 01:19
@exs6350 thank you for your feedback, I just (a few seconds ago) pushed a first fix.
Can you tell me if you still experience the issue?

**Comment by exs6350** [comment] 2017-08-11 01:58
@blandinw Issue seems to be fixed validation is working again

**Comment by blandinw** [comment] 2017-08-11 07:04
@denzils a proper fix has been deployed. Can you confirm that the issue is fixed for you?

**Comment by blandinw** [comment] 2017-08-11 16:28
Closing now. Please feel free to reopen

**Closed by blandinw** 2017-08-11 16:28 UTC
Labels: bug, investigating

**Comment by denzils** [comment] 2017-08-11 22:56
Thank you!!!
