### ISSUE TITLE
Facing issue to train the entities

### ISSUE THREAD

**Issue by noumanbsc125** [wit-ai/wit#921] opened 2018-01-14 05:04 UTC
Hi,
  We are facing issue while training the entities, Below is one entity from my application which is having multiple entity values with lots of expressions, Most of the expressions are working fine but some are not working after multiple attempts of training. 

Entity = **Trasfer_weapon_ownership_description**
Expression = **transfer weapon ownership terms and conditions**

Can you please let us know why are they not getting trained, are we doing something wrong ?

AppID = 59ec54b8-dcc2-4718-8d4b-763aafd9acef

**Comment by paulopadopalos** [comment] 2018-01-14 15:47
I can confirm I'm having the same issue for AppID=5a08911b-1b20-43d3-886c-2e9056e8b6cc.

Despite repeatedly training the bot with the same message over and over again, it's never learning the intent.

**Comment by stopachka** [comment] 2018-01-15 13:14
Hey @paulopadopalos -- This kind of issue could be caused by many reasons. If you could open up an issue, with your app id, an example sentence, and what you expected, we can better diagnose your issue

**Comment by noumanbsc125** [comment] 2018-01-15 17:40
Any update on my issue.

**Comment by noumanbsc125** [comment] 2018-01-18 20:35
@stopachka please any update on my issue.

**Comment by stopachka** [comment] 2018-01-21 23:24
Hey @noumanbsc125, we'll update here what we find. Your app has more then 100 entities, which may be surfacing new bugs from Wit.

**Comment by noumanbsc125** [comment] 2018-02-06 19:43
@stopachka plz any update.

**Comment by blandinw** [comment] 2018-02-07 00:04
@noumanbsc125 I'm looking into it and update you shortly, thank you for your patience!

**Comment by blandinw** [comment] 2018-02-07 16:47
@noumanbsc125 The issue arises because your app has so many different entities.
I'm working on a fix on my end, but it seems that your app will be working suboptimally with the current entity structure.

Why do you need so many different trait entities? Why not only have one `intent` entity with many values? Or a couple entities to capture `intent` (description) and e.g. `topic` (license_renewal)?

**Comment by blandinw** [comment] 2018-02-08 17:21
@noumanbsc125 the way you structured your app leads to 100+ very low confidence entities, instead of 1 strong `intent` entity. See my suggestion above.
In the meantime, I have retrained your (suboptimal) app and you can get low confidence entities by providing `?n=2` when querying the API.

Closing, please open another issue if we can help further.

**Closed by blandinw** 2018-02-08 17:21 UTC
Labels: bug, investigating
