### ISSUE TITLE
Diacritics stopped working, cannot remove samples

### ISSUE THREAD

**Issue by RisaI** [wit-ai/wit#1618] opened 2020-01-04 11:54 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
report a *bug*

**What is the current behavior?**
Diacritics used in new samples now get replaced with '?'. Furthermore, I cannot remove these invalid samples from the model. When I click the delete button, the entry disappears, only to reappear when I refresh the site.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Paste 'aábcčdďeéěfghchiíjklmnňoópqrřsštťuúůvwxyýzž' as a new example and validate it. Now look in the used samples. Try to remove this sample and then refresh the site.

**What is the expected behavior?**
Diacritics and sample removal working as it did yesterday.

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by eurocharts** [comment] 2020-01-04 14:21
I have the same bug. All new samples replaced with ???? without chance to remove them.

**Comment by aforaleka** [comment] 2020-01-05 02:04
thanks for reporting the issue, looking into this!

**Comment by hno1993** [comment] 2020-01-07 11:10
same as my application, I think it caused by a new update

**Comment by doriclaudino** [comment] 2020-01-07 11:11
Waiting for this solution @doriclaudino

**Comment by 91ns** [comment] 2020-01-08 07:19
any updates on this issue?

**Comment by lycai-fb** [comment] 2020-01-08 19:48
We are still investigating. Looks like it might be a database-layer issue.
Thanks for your patience.

**Comment by doriclaudino** [comment] 2020-01-08 21:05
@lycai-fb 
The api responds correctly
The /logs shows the correctly
The /semantic not show the accents

Maybe it help

**Comment by jtliao** [comment] 2020-01-10 00:00
We've found the underlying issue, and are working on a fix. We sincerely apologize for the inconvenience, it turned out to be very challenging to unroot the problem.

**Comment by RisaI** [comment] 2020-01-10 19:22
It seems all of the new samples are fixed, but all previous samples are now gibberish.

![image](https://user-images.githubusercontent.com/7413196/72180158-dce96780-33e6-11ea-9eb7-fca52deffe60.png)

**Comment by jtliao** [comment] 2020-01-10 20:49
checking... @RisaI what is your app ID and what is the expected text for those two samples?

**Comment by doriclaudino** [comment] 2020-01-10 20:57
@jtliao got the same problem

it:
*DoaÃ§Ã£o em Medford.* VÃ¡rios itens

should be: 

> ***Doação em Medford.* Vários itens**


msg_id: 1NahBoJTfWNM1Spnq
app_id: 3385537998125206

**Comment by hno1993** [comment] 2020-01-10 21:41
the current sample was fixed but the previous ones changed to unknown Unicode 

![image](https://user-images.githubusercontent.com/44380685/72186845-38c3e880-3407-11ea-94d6-87d5aa2b0cac.png)

please fix it

**Comment by AssDestroyer1994** [comment] 2020-01-13 08:31
Same issue as @hno1993 and @RisaI 
new entities are fixed (by the logs), but previous entities in the Inbox still incorrect
Is it possible to delete all previous incorrect entities from the Inbox or maybe another solution?
![3](https://user-images.githubusercontent.com/59081516/72241517-1513c480-35f8-11ea-8cb2-0c1a7a103b6d.png)
![2](https://user-images.githubusercontent.com/59081516/72241520-1513c480-35f8-11ea-8db0-51d557d4cf43.png)

**Comment by TiPOKgg** [comment] 2020-01-13 08:41
Same issue as @hno1993 and @RisaI
new entities are fixed (by the logs), but previous entities in the Inbox still incorrect
Is it possible to delete all previous incorrect entities from the Inbox or maybe another solution?
![3](https://user-images.githubusercontent.com/59081516/72242079-8acc6000-35f9-11ea-9862-5c093fcb49a1.png)
![2](https://user-images.githubusercontent.com/59081516/72242080-8acc6000-35f9-11ea-98e9-31c21341a2c0.png)

Language: Russian
App ID: 2895389950492503

**Comment by hno1993** [comment] 2020-01-15 14:15
any update about this problem?

**Comment by ducla2** [comment] 2020-01-16 01:33
The UTF-8 strings are converted to ASCII. 
mÃ¬nh se tráº£ -> It should be "mình se trả"
is there any migration db from nvarchar to varchar?

**Comment by FengyangZhang** [comment] 2020-01-16 01:39
We've found the real cause of this issue and are actively working on it, expect this to be fixed soon. Thanks for the patience!

**Comment by eurocharts** [comment] 2020-01-16 15:57
All samples and inbox again replaced with ??????????

**Comment by FengyangZhang** [comment] 2020-01-16 18:14
@eurocharts Can you provide the app ID? Also any chance those samples are entered recently (one or two weeks before)? Samples entered in this timeframe are not fixed yet and will be fixed soon

**Comment by eurocharts** [comment] 2020-01-16 18:43
app ID = 2184728738274083

cannot clear Inbox to see latest messages

**Comment by doriclaudino** [comment] 2020-01-17 14:32
Time to migrate from wit?

All my data is compromised. I'm waiting for 2 weeks and I can't train or even export my projects because all data is wrong. The problem is even bigger if someone try to update their data. The lookup is a substring from position X,Y which means a single emoticon is replaced by 8 new characters, soo it can make users lost a lot of work or update to a wrong lookup strings.

I'm opening to help, but there's a lack of updates here as well.

**Comment by doriclaudino** [comment] 2020-01-17 14:49
@FengyangZhang 
appid: 3385537998125206

got samples correct (old) , 1-2 weeks old, and samples to classify as well.

**Comment by doriclaudino** [comment] 2020-01-17 15:06
for a crosscheck

/logs still correct 

![image](https://user-images.githubusercontent.com/3863501/72622326-44ea0180-3943-11ea-891c-9f73cab30686.png)

**Comment by hno1993** [comment] 2020-01-19 11:41
hey developers, thank you all for the efforts, 
the inbox receive the Expressions correctly and I can validate them <3, but I notice that the accuracy of the previously trained entities is not as it used to be :(

the samples I have added to the app in the previous two weeks would not be deleted? they remain question marks in the samples section...

I know you all working to fix this issue, but please my graduation project relies heavily on this app and it takes a lot of time from me waiting and retraining the entities.

**Comment by eurocharts** [comment] 2020-01-21 15:49
still question marks, and cannot remove them from inbox.... So long...

App ID: 2184728738274083

**Comment by FengyangZhang** [comment] 2020-01-21 23:49
@eurocharts All of your samples should have been fixed, do let me know if you still see something broken. I'm running a bigger script that will update everybody's samples, hopefully everything should be fixed by tonight.

**Comment by eurocharts** [comment] 2020-01-22 05:21
> @eurocharts All of your samples should have been fixed, do let me know if you still see something broken. I'm running a bigger script that will update everybody's samples, hopefully everything should be fixed by tonight.

This is my inbox right now...

![witai](https://user-images.githubusercontent.com/49547641/72867481-23e13200-3cf0-11ea-8fb4-b78ed40a8fd6.png)

**Comment by doriclaudino** [comment] 2020-01-23 14:11
@FengyangZhang not fixed for me :(

**Comment by stevemulligan** [comment] 2020-01-24 02:33
I have many entries with question marks that can not be deleted

app id: 1938280796272124

**Comment by idanadut** [comment] 2020-01-24 17:28
Hi,
@FengyangZhang not fixed for me either.
It was fixed around a week or week and a half ago or so, then after a few days later the "???" came back
App Id: 2646309675417270. Language: Hebrew

**Comment by hno1993** [comment] 2020-01-26 04:35
I still have question mark samples (it can't be deleted)... 
everything other than that work as usual 

the language: Arabic
the app id: 3179188082152056

**Comment by FengyangZhang** [comment] 2020-01-28 05:00
Sorry about the inconvenience this has caused, you should now be able to delete the samples. On the other hand we are still working to restore the samples to correct encodings.

**Comment by hno1993** [comment] 2020-01-28 06:12
> Sorry about the inconvenience this has caused, you should now be able to delete the samples. On the other hand we are still working to restore the samples to correct encodings.

thank you, I was able to delete them

**Comment by idanadut** [comment] 2020-02-03 16:35
Hi,
still getting this for a few weeks now, so I cannot fix my app
App Id: 2646309675417270. Language: Hebrew.

Do you know when it could be fixed?

Thanks!

![questionmarkwit](https://user-images.githubusercontent.com/44604937/73671512-c5cf2a00-46b3-11ea-8beb-6690f518ea18.png)

**Comment by FengyangZhang** [comment] 2020-02-06 18:17
We've completed a scan and fix on all data, note there might be a few entries that's not fixed or still shows incorrect text, please delete them manually, sorry for the inconvenience. I'll close this issue if no more comments.

**Closed** 2020-02-10 19:48 UTC
Labels: bug, investigating
