### ISSUE TITLE
I cannot review my live utterances

### ISSUE THREAD

**Issue by emreisik95** [wit-ai/wit#1935] opened 2020-10-05 11:52 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

Bug

**What is the current behavior?**

https://imgur.com/kl1rK45 I cannot click the details button. I tried it with Chrome 85.0.4183.121 (64-bit) and Safari (On macOS Big Sur Beta 9)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

https://imgur.com/63fmvsY

**What is the expected behavior?**

Open the details and select the intent

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

2791794717744794

**Comment by andersmattson** [comment] 2020-10-05 13:25
Same issue here, on MacOS Catalina in both Safari and Chrome.

Javascript error when clicking the button:
```
ErrorUtils caught an error:

Got unexpected null or undefined
```

**Comment by ruoyipu** [comment] 2020-10-05 17:57
Thanks for the report! I can repro, and we are investigating right now.

**Comment by ruoyipu** [comment] 2020-10-05 22:58
The fix has landed. Please do a hard refresh to get the latest version of the site and the down arrow should work now.
Let us know if there are any other issues. Thanks!

Duplicate of #1933

**Closed as completed by ruoyipu** 2020-10-05 22:58 UTC
Labels: bug, investigating
