### ISSUE TITLE
Faulty predictions when using Composite Entities.

### ISSUE THREAD

**Issue by Hyperclaw79** [wit-ai/wit#905] opened 2018-01-03 22:05 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
Even after training the same expression repeatedly with the correct entitites and their composition, the detection is always incorrect for the same expression.

For example, my expression is `Numb by Linkin Park`.
I have an entity `data` which detects in the format *song* by *artist* , `song` entity which detects the song and `artist` which detects the artist. All 3 are of the type `free-text`.
No matter how many times I train the expression as:
>data: Numb by Linkin Park
>>song: Numb
>>artist: Linkin Park

It either returns:
>song: Numb
>data: by Linkin Park
>>artist: Linkin Park

Or as:

>song: Numb
>artist: by Linkin Park

Also,  
If I try it with `Tell me about Numb by Linkin Park`
It detects perfectly as:
>data: Numb by Linkin Park
>>song: Numb
>>artist: Linkin Park

This error started happening from a few hours ago. The detection was working perfectly fine yesterday.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a new expression `Numb by Linkin Park`. it gets detected as a faulty one initially. Correct the detection and validate. Re-enter the same expression.

**What is the expected behavior?**
The entities should learn from the corrected entities for the expression. 

Also, I'd like to refrain from using `keyword` as lookup strategy because it will cause conflicts when an artist or a song have same names like XYZ the song and XYZ the singer.

**What is the App ID where you are experiencing this issue (if applicable)?**
5a43c34d-86c3-40d6-8714-628a307abc9e

**Comment by magnusburton** [comment] 2018-01-05 17:46
Having the same issue. Even after training on the same kind of sentence (structured exactly the same) it won't even predict the composite entities. Only the `data` entity for me (taking from your example). So I get a prediction för `data` and I manually have to fill in the `song` and `artist` for every single expression.

**Comment by Hyperclaw79** [comment] 2018-01-05 18:01
>I manually have to fill in the `song` and `artist` for every single expression.
Despite which, it still won't learn. This defeats the whole purpose of using an NLP. 😕

**Comment by blandinw** [comment] 2018-01-08 17:26
Looking into it

**Comment by patapizza** [comment] 2018-01-08 22:59
@magnusburton @Hyperclaw79 What is your app id?

**Comment by magnusburton** [comment] 2018-01-09 00:56
@patapizza /magnusburton/Lisa_Disturbances Thanks!

**Comment by Hyperclaw79** [comment] 2018-01-09 07:06
@patapizza 5a43c34d-86c3-40d6-8714-628a307abc9e

**Comment by patapizza** [comment] 2018-01-10 01:27
@Hyperclaw79 This is actually a duplicate of https://github.com/wit-ai/wit/issues/902.

@magnusburton Found a possible cause, will give another stab at it tomorrow.

**Comment by Hyperclaw79** [comment] 2018-01-10 06:43
@patapizza I don't think it is a duplicate. The issues might have rooted out from the same app and scenario but #902 is a feature request to prioritize entities. This one is actually a bug in detection. The only common factor is the use of composite entities.

**Comment by patapizza** [comment] 2018-01-12 02:27
@magnusburton The `affected` entity should behave better now.

**Comment by magnusburton** [comment] 2018-01-12 12:28
@patapizza Works great now, thanks a lot.

**Closed** 2018-01-26 21:48 UTC
Labels: bug, investigating
