### ISSUE TITLE
PUT entities/intent not updating values

### ISSUE THREAD

**Issue by kumangxxx** [wit-ai/wit#1256] opened 2018-11-01 15:29 UTC
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
calling ```PUT /intents``` doesnt update the intents

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

call ```PUT /intents``` api
```
curl -X PUT \
  'https://api.wit.ai/entities/intent?v=31/08/2017' \
  -H 'Authorization: Bearer $TOKEN' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: a81f93ed-2c2b-4ada-89a4-b7e1ccdfb0ad' \
  -d '{
  "values": [
    {
      "value": "Third Intent",
      "expressions": [
        "third",
        "ketiga",
        "ketigax",
        "tiga",
        "tres",
        "trio"
      ]
    },
    {
      "value": "Second Intent",
      "expressions": [
        "second",
        "kedua",
        "keduax"
      ]
    },
    {
      "value": "First Intent",
      "expressions": [
        "first",
        "pertama",
        "pertamax"
      ]
    }
  ]
}'
```

call ```GET /intents``` API

```
curl -X GET \
  'https://api.wit.ai/entities/intent?v=31/08/2017' \
  -H 'Authorization: Bearer B6QAOZU6AQTQ2NAY2QEBFTFX5BYEDLNF' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 79ef169e-c5e4-4a30-a1e6-95e3ed8372ec'
```
the GET api will return different result (old result). in app dashboard, the training status is always 'Done'

**What is the expected behavior?**
the PUT api updates the intens

**What is the App ID where you are experiencing this issue (if applicable)?**
1751234094986442

**Comment by stopachka** [comment] 2018-11-01 19:06
Hey @kumangxxx looking into this. 

Here is what I repro'd: 
- Made a request with "Fourth, Fifth, Sixth" intent
- The table called "values" *did* update
- However, the example sentences "first" "pertama" etc, had the old values in there

(please confirm if this is indeed what you saw, and not a different bug -- in the meantime will look further into this)

**Comment by kumangxxx** [comment] 2018-11-02 07:30
Yes, my issue is basically expressions didn't update

@stopachka

**Comment by blandinw** [comment] 2018-11-02 19:12
@kumangxxx Thank you for your feedback and patience!

There was a bug in the implement of `PUT /entities` for existing samples. We pushed a patch yesterday night which should fix it.

Feel free to reply here if you still experience any unexpected behavior.

**Comment by jtliao** [comment] 2018-11-02 19:44
Unfortunately, only part of the problem was addressed, a full fix will be out soon-- will notify once it is out.

**Comment by jtliao** [comment] 2018-11-03 02:38
hey @kumangxxx this should be fixed now, feel free to re-open if you're still seeing issues.

**Closed by jtliao** 2018-11-03 02:38 UTC

**Comment by blandinw** [comment] 2018-11-07 20:29
(discussed in #1261)
